### ISSUE TITLE
web播放缩放0.5的透明视频会有黑影

### ISSUE THREAD

**Issue by zhouxiaopan** [Tencent/vap#100]
同一套素材，web播放缩放0.5的透明视频会有黑影，客户端没问题

https://user-images.githubusercontent.com/19689244/122006270-35494380-cde9-11eb-999f-4de9d014eff4.mp4

**Comment by hujinliang** [comment]
0.5视频的alpha通道部分比较小，如果尺寸按照1来进行展示那么alpha通道部分的纹理会出现模糊或者像素化的行为最终影响展示效果，可以调整成按照0.5尺寸来展示
