### ISSUE TITLE
[iOS]从后台恢复时等待时间过长，CPU飙升，低端机卡死甚至崩溃

### ISSUE THREAD

**Issue by Styx-S** [Tencent/vap#102]
1. iOS退后台VTSession失效，重建的方式是从Seek到前一个关键帧，从关键帧开始解码到暂停前帧，这个过程无法避免
2. 需要解码的帧数受视频中关键帧分布的影响（VAP制作工具使用ffmpeg默认设置，这里不太好改）；或者屏蔽低端机型，使低端机型在退后台时直接结束，而不是暂停
3. 为UIView+VAP添加一个设置，用户可在开始播放前根据情况自行设置是退后台暂停还是退后台结束（默认为结束）

**Comment by githublsy** [comment]
mark
