### ISSUE TITLE
可以跟字节的Alphaplayer项目对比一下吗？

### ISSUE THREAD

**Issue by gaojiecai** [Tencent/vap#106]
https://github.com/bytedance/AlphaPlayer

**Comment by hexleo** [comment]
没有做过详细数据对比，从功能与原理简单说下我的看法：
Android性能：
1 解码性能：都是基于H264解码，原理基本相同，所以解码性能不会有太大差异
2 内存：主要内存消耗 TextureView与硬件解码器，VAP也都有使用，内存应该也不会有太大差异
从性能上看基本不会差别太大

功能方面：
1 普通的透明动画能力（都具备）
2 VAP支持融合动画，可以在视频中加入自定义图片

素材方面：
1 提供有完整的素材制作工具
2 从素材制作方面有比较多的积累，主要有：1）视频分辨率16字节对齐保证；2）视频元素边界预留（保证在量化过程中边界不会倍模糊掉）；3）支持0.5 alpha区域，减小视频分辨率；

平台方面：
我们提供 Android iOS Web 3个主流平台
