### ISSUE TITLE
mac vapxTool 生成vap文件报错

### ISSUE THREAD

**Issue by Etoile984816138** [Tencent/vap#114]
# mac vapxTool 生成vap文件报错

1. 问题描述（重现路径）
上传视频后，点击生成报错，使用测试素材也会复现
![image](https://user-images.githubusercontent.com/19284985/125784380-0ae96ace-6d19-4229-8f4e-c8bcb60c39b9.png)
![image](https://user-images.githubusercontent.com/19284985/125784521-c7f95314-6614-4897-a2a4-6a62494706a6.png)

2. 运行环境（手机型号，Android/iOS版本等）
macOS版本  11.2.3 

3. 相关日志
4. 播放错误的文件（可选）

# issue template

1. Problem description 
2. Running environment (mobile phone model, Android/iOS version, etc.)
3. Logs
4. Error file (optional)

**Comment by hexleo** [comment]
mac版本不维护了，可以使用最新的java版本
