### ISSUE TITLE
播放多个文件时，导致的奇怪问题

### ISSUE THREAD

**Issue by frank1989678** [Tencent/vap#115]
# issue 模版

1. 点击播放按钮
2. 点击右上角关闭按钮
3. 再次点击播放按钮
4. 问题重现
![报错信息截图](https://user-images.githubusercontent.com/10068764/125795993-8d9138ed-10df-44fd-8e56-76062717bbe1.png)

demo可以直接将下面的附件文件放入到src文件夹下面运行

[Anim.vue.txt](https://github.com/Tencent/vap/files/6823361/Anim.vue.txt)
[Skin.vue.txt](https://github.com/Tencent/vap/files/6823364/Skin.vue.txt)
[HelloWorld.vue.txt](https://github.com/Tencent/vap/files/6823366/HelloWorld.vue.txt)

**Comment by hujinliang** [comment]
看了下代码，type不能这么用，这个type作用是同一个页面不同的位置可能同时播放时候，这时候需要创建新的上下文来播放；如果是同一个位置，那type保持一致就好了。浏览器支持的context数量有限，数量可以通过以下方法判断，比如可能是16个
![image](https://user-images.githubusercontent.com/17648734/125882009-ca3681a9-36d1-4a19-be7a-60ce6d70369c.png)，如果你必须要这么用的话，需要改下**clearMemeoryCache**方法
![image](https://user-images.githubusercontent.com/17648734/125882686-66e9afb8-4adb-43d4-a912-01e8a92f4a4c.png)
