### ISSUE TITLE
web端融合动画，图片和动画移动不同步

### ISSUE THREAD

**Issue by Man-Gold** [Tencent/vap#117]
![image](https://user-images.githubusercontent.com/34513866/126733708-948000c0-d50f-4599-8cfe-5e170640022e.png)

MP4：
[output.zip](https://github.com/Tencent/vap/files/6866381/output.zip)

视频效果：

https://user-images.githubusercontent.com/34513866/126734272-b791c196-b298-4816-a2d6-c664c4f3c007.mov

**Comment by hujinliang** [comment]
传入的fps参数值应该是24，要和生成的config文件中的fps保持一致
