### ISSUE TITLE
现在部分旧款安卓的手机，当播放带有插入图片或者文字的动画时会出现分层的现象，左中右三层，是什么原因呢，有人知道吗

### ISSUE THREAD

**Issue by unknowntc** [Tencent/vap#123]
# issue 模版

1. 问题描述（重现路径）
2. 运行环境（手机型号，Android/iOS版本等）
3. 相关日志
4. 播放错误的文件（可选）

# issue template

1. Problem description 
2. Running environment (mobile phone model, Android/iOS version, etc.)
3. Logs
4. Error file (optional)

**Comment by unknowntc** [comment]
http://test-game-play.oss-cn-hangzhou.aliyuncs.com/temp/2021/7/30/4110935dc9f94b5590bddedd08426d75.mp4

**Comment by hexleo** [comment]
我在Android demo里测试是能正常播放。你先确认下是不是不是下载后文件被篡改了，检查下md5。你这个是用老版工具本生成的吧，老版本工具不维护了，建议使用新版本，而且老版本生成的视频文件分辨率太大了，有些手机对高分辨率的视频支持不好，也可能导致画面异常。

**Comment by unknowntc** [comment]
> 我在Android demo里测试是能正常播放。你先确认下是不是不是下载后文件被篡改了，检查下md5。你这个是用老版工具本生成的吧，老版本工具不维护了，建议使用新版本，而且老版本生成的视频文件分辨率太大了，有些手机对高分辨率的视频支持不好，也可能导致画面异常。

新版在哪里  默认进去是新版吗？

**Comment by hexleo** [comment]
tool目录下有最新版本下载，目前是tool2.0.2
https://github.com/Tencent/vap/tree/master/tool
