### ISSUE TITLE
外部急需一个字段判断当前MP4动画是否正在播放!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by CoderLineChan** [Tencent/vap#131]
1、更新1.0.13后,hwd_isFinish无法获取到最新的是否播放状态,外部很多地方需要用到是否正在播放来判断是否需要播放新的动画,来过滤掉同一个资源多次调用播放问题
2、新增的hwd_enterBackgroundOP在QGVAPWrapView中无法直接设置,其属性属于vapView而并非QGVAPWrapView,

**Comment by Styx-S** [comment]
1. （本身hwd_isFinish就不是对外暴露的吧）无法取到播放状态的原因是 加入了暂停还是其他的？ 可以说明下这里“是否正在播放来判断是否需要播放新的动画,来过滤掉同一个资源多次调用播放问题”具体是什么场景吗，为什么会根据当前没有播一个资源就去新增一个播放呢
2.  我们后续补充一下获取当前是否在播放的接口和QGVAPWrapView的相关能力

**Comment by CoderLineChan** [comment]
1、场景是这样的: 我是一个无限播放的MP4动画,这个动画是根据后台返回的资源播放,而且这是一个实时刷新的视图, 所以这边不需要实时的调用播放动画的方法.

**Comment by Styx-S** [comment]
> hwd_isFinish无法获取到最新的是否播放状态

所以在你的场景里面，认为暂停也不算在播放吗。那你可以同时取hwd_onPause的值进行判断
因为这也涉及到 如果加入一个接口来判断是否正在播放，那么还未结束但暂停了的场景是否是pause的语义问题

**Comment by sauchye** [comment]
@hexleo @bin
两位大佬，iOS 是否可以暴露方法解决后台播放以及viewWillDisappear后stop，支持后台播放
