### ISSUE TITLE
android 9.0 播放demo.mp4 出现0x2 MediaCodec exception e=android.media.MediaCodec$CodecException:

### ISSUE THREAD

**Issue by lklgithup** [Tencent/vap#132]
android 9.0设备 运行 vap demo 出现0x2 MediaCodec exception  #e=android.media.MediaCodec$CodecException:异常无法播放
![Uploading P181(SW6F%4~Y%(DF[DE4ZO.png…]()

**Comment by lklgithup** [comment]
34.303 E/AnimPlayer.HardDecoder(21780): MediaCodec configure exception e=android.media.MediaCodec$CodecException: start failed
08-13 15:41:34.303 E/AnimPlayer.HardDecoder(21780): android.media.MediaCodec$CodecException: start failed
08-13 15:41:34.303 E/AnimPlayer.HardDecoder(21780): 	at android.media.MediaCodec.native_start(Native Method)
08-13 15:41:34.303 E/AnimPlayer.HardDecoder(21780): 	at android.media.MediaCodec.start(MediaCodec.java:2068)
08-13 15:41:34.303 E/AnimPlayer.HardDecoder(21780): 	at com.tencent.qgame.animplayer.HardDecoder.startPlay(HardDecoder.kt:166)
08-13 15:41:34.303 E/AnimPlayer.HardDecoder(21780): 	at com.tencent.qgame.animplayer.HardDecoder.access$startPlay(HardDecoder.kt:29)
08-13 15:41:34.303 E/AnimPlayer.HardDecoder(21780): 	at com.tencent.qgame.animplayer.HardDecoder$start$1.run(HardDecoder.kt:57)
08-13 15:41:34.303 E/AnimPlayer.HardDecoder(21780): 	at android.os.Handler.handleCallback(Handler.java:873)
08-13 15:41:34.303 E/AnimPlayer.HardDecoder(21780): 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-13 15:41:34.303 E/AnimPlayer.HardDecoder(21780): 	at android.os.Looper.loop(Looper.java:193)
08-13 15:41:34.303 E/AnimPlayer.HardDecoder(21780): 	at android.os.HandlerThread.run(HandlerThread.java:65)
08-13 15:41:34.304 E/AnimPlayer.Decoder(21780): onFailed errorType=10002, errorMsg=0x2 MediaCodec exception e=android.media.MediaCodec$CodecException:

**Comment by hexleo** [comment]
每次运行必现吗？是运行demo里哪个视频？手机具体型号是什么？

**Comment by lklgithup** [comment]
运行的demo.mp4  不是手机是Android 9.0 盒子

**Comment by hexleo** [comment]
电视盒子？什么型号的电视盒子？

**Comment by lklgithup** [comment]
创维的 e900v22e

**Comment by lklgithup** [comment]
这个问题复现步骤是 上面先用系统
mediaplayer播放视频在下滑到透明动画就会必现

**Comment by hexleo** [comment]
没有这样的机器，猜测应该是机器兼容问题，或者是有硬件解码限制之类，你们可以试试用demo同时播放两个vap，看看是否会有问题
