### ISSUE TITLE
某些动效播放不了

### ISSUE THREAD

**Issue by wangkai4090** [Tencent/vap#133]
[动效.zip](https://github.com/Tencent/vap/files/6991264/default.zip)
这个两个动效播放不了，能看下是什么原因吗

**Comment by wubiner** [comment]
你是说iOS播放不了是么，看到你的这两个素材里都没有vapc 这个box，你是用的哪一个版本的vap生成工具做的呢？

**Comment by wangkai4090** [comment]
[4903.zip](https://github.com/Tencent/vap/files/6991615/4903.zip)
是iOS播放不了，安卓可以播放，这个是找外包做的，我不太清楚，这个动效是可以播放的，和不能播放的有什么区别吗

**Comment by wangkai4090** [comment]
![image](https://user-images.githubusercontent.com/45187987/129550625-c1c9834a-c8c0-49a8-bf2d-0e8c6aa2034a.png)
这是用demo跑的播放不了的打印信息

**Comment by wubiner** [comment]
你这个素材，我看了一下，iOS这边解析mp4 box都是错误的，所以iOS这边无法播放。

**Comment by wangkai4090** [comment]
![image](https://user-images.githubusercontent.com/45187987/129550913-bac3df1b-cbce-4a92-b28f-098372df9c66.png)
你说的box是这个打印信息吗，但是能播放的也有这个打印

**Comment by wubiner** [comment]
我说的意思是这个素材里的box均无法被iOS正确解析，拿不到sps、pps等这些数据

**Comment by wangkai4090** [comment]
好的，谢谢，我再找外包看看

**Comment by wangkai4090** [comment]
我问了外包他说使用AE导出的，有什么问题吗，其他的动效都没问题，就这两个播放不了

**Comment by wubiner** [comment]
麻烦把用的vap工具版本告知一下

**Comment by wangkai4090** [comment]
他说不知道啥时vap。。

**Comment by wubiner** [comment]
就是你们用这个vap组件去播放特效，那生成这个特效的素材也必须是用vap提供的vap tool生成的。https://github.com/Tencent/vap/tree/master/tool

**Comment by wubiner** [comment]
你好，刚刚用其他工具分析了一下你提供的素材，发现你提供的素材的mdat这个box的length比较特殊，iOS这边解析mp4是自己解析的，解析box时固定按照length是前4字节，type是紧接着的后4字节。所以解析到mdat时，解析得到的length就认为只有1，故而导致之后所有的解析都错误了。

**Comment by wangkai4090** [comment]
你好，那这个问题怎么解决呢，只能通过修改动效素材吗

**Comment by wubiner** [comment]
需要修改一下源码，把解析box的逻辑修复一下。或者就是修改素材。

**Comment by wangkai4090** [comment]
修改源码的话是在哪个文件里呢，需要怎么修改，或者你们方便修改一下吗

**Comment by wubiner** [comment]
最近这两天会修复这个问题，QGMP4Parser.m文件中的readBoxTypeAndLength方法需要修复一下取length的逻辑

**Comment by wangkai4090** [comment]
好的，谢谢

**Comment by wubiner** [comment]
master分支已经修复了，tag是iOS1.0.14版本。这里为了引起开发者注意，特别添加了一个enableOldVersion接口，所以你更新代码以后，如果还是要播放这些没有vapc box的素材，那就需要在play之前调用一下这个接口，设置enable。如果没有特殊需求，建议使用我们提供的vap工具来制作素材，以避免类似不兼容异常。

**Comment by wangkai4090** [comment]
好的，谢谢，我这还有一个问题，在当前页面播放的时候，我进入下一页面，动效会停止播放，返回上一页面会卡在那一帧
![image](https://user-images.githubusercontent.com/45187987/129699655-6b578153-4bcb-42e6-9fa8-244fa80e85d7.png)

**Comment by wubiner** [comment]
你实现了HWDMP4PlayDelegate里的viewDidStopPlayMP4:view 方法了么？有在里面移除view没？如果有的话，那是你从一个vc push到另一个vc复现的么？

**Comment by wangkai4090** [comment]
实现了，没有在里面移除view，我想返回播放页面的时候动效继续播放，不会停止，我看到有pauseHWDMP4和resumeHWDMP4这两个方法，但是没看到有判断当前状态是否在播放的方法

**Comment by wubiner** [comment]
你试一下判断hwd_onPause和hwd_isFinish能不能符合你的要求。这两个属性目前在.m文件定义，你可以移到.h

**Comment by wangkai4090** [comment]
好的，我试试，谢谢

**Comment by hexleo** [comment]
已在iOS 1.0.14版本解决此问题
