### ISSUE TITLE
建议视频帧给个名称命名

### ISSUE THREAD

**Issue by AulusCaelius** [Tencent/vap#135]
me等传统的导出视频帧前面都是有名称的，000.png 001.png这样命名不科学。建议命名成为 名称000.png、名称001.png。

**Comment by AulusCaelius** [comment]
一个一个改帧名称十分低效，还是说你们有其他方法？

**Comment by hexleo** [comment]
不同工具导出规范都不一样，所以我们定义一套规范，无论哪个工具导出，只要符合我们的规范就好

**Comment by AulusCaelius** [comment]
不是，我很多工具导出不了你们的规范要求的格式啊，一般文件输出文件都要设置输出名称啊，无法空值名字输出啊。都要一个个把前缀的名称删除。你们是用什么视频导出工具的？
