### ISSUE TITLE
X5内核播放mp4 只有声音无视频内容

### ISSUE THREAD

**Issue by Marla62** [Tencent/vap#136]
# X5内核浏览器播放mp4  只有声音无视频内容 

1. 问题描述（重现路径）
在UC浏览器中 播放有声音的VAP
2. 运行环境（手机型号，Android/iOS版本等）
安卓10 UC浏览器V13.5..1134
3. 相关日志
无
4. 播放错误的文件（可选）
任意一个有声音的MP4（官方演示的第三个案例：烛台视频可复现)

另：发现在X5内核的浏览器中会出现问题

**Comment by hexleo** [comment]
是这个问题吗？这样能解决你的问题吗？
![image](https://user-images.githubusercontent.com/3285051/131767831-daabf1e6-30c1-48b6-b123-de71b59156b5.png)

**Comment by Marla62** [comment]
> 是这个问题吗？这样能解决你的问题吗？ ![image](https://user-images.githubusercontent.com/3285051/131767831-daabf1e6-30c1-48b6-b123-de71b59156b5.png)

是这样解决的。这是我在QQ群里发布的解决方案。
