### ISSUE TITLE
Mi9 只显示第一帧无法播放并且花屏

### ISSUE THREAD

**Issue by lwj1994** [Tencent/vap#143]
1. 问题描述（重现路径）：只显示第一帧无法播放并且花屏。

![image](https://user-images.githubusercontent.com/10978048/132444181-1a5ec2d9-9a11-493d-a878-bfd054bd5015.png)

2. 运行环境（手机型号，Android/iOS版本等）MI9 MIUI 12.0.2 稳定版  Android 10。vap version:2.0.19
3. 相关日志:  日志显示是正常播放的，但是只渲染了第0帧和第1帧
```java
onVideoRender,0,100
onVideoRender,1,100
onVideoRender,0,100
onVideoRender,1,100
onVideoRender,0,100
onVideoRender,1,100
onVideoRender,0,100
onVideoRender,1,100
onVideoRender,0,100
onVideoRender,1,100
onVideoRender,0,100
onVideoRender,1,100
```

4. 播放错误的文件（可选）：h264，分辨率：688 × 704

**Comment by hexleo** [comment]
能把素材文件发出来看看吗？所有视频播放都会这样，还是只有这一个视频这样

**Comment by lwj1994** [comment]
@hexleo  目前只发现 这个视频在该机型上出现这样的问题。https://apk.poizon.com/duApp/Android_Config/animation/community/community_tag_introduce_bg.mp4

**Comment by hexleo** [comment]
我这没有mi9这个手机，只有mix3，没有重现这个问题，能不能把完整的运行过程中的日志发出来

**Comment by lwj1994** [comment]
加了Alog准备看日志，重新打完包又没问题了..
