### ISSUE TITLE
崩溃问题：UIView.hwd_delegate.getter()

### ISSUE THREAD

**Issue by borischou** [Tencent/vap#146]
崩溃信息：
OS Version: iOS 14.4.2 (18D70)
Report Version: 104

Exception Type: EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: SEGV_NOOP
Crashed Thread: 38

Application Specific Information:
addObject: > countByEnumeratingWithState:objects:count: > retainWeakReference >
Attempted to dereference garbage pointer .
Originated at or in a subcall of unknown, cannot find symbol

崩溃堆栈：
Thread 38 Crashed:
0   libswiftCore.dylib              0x1a62a4f9c         swift_getObjectType  + 48
1   libswiftCore.dylib              0x1a5f9dad8         [inlined] $ss018_bridgeAnyObjectToB0yypyXlSgF
2   libswiftCore.dylib              0x1a5f9dad8         $ss018_bridgeAnyObjectToB0yypyXlSgF
3   custom                        0x208d9cd68         UIView.hwd_delegate.getter  (UIView+VAP.swift:427)
4   custom                        0x208d9cce0         @objc UIView.hwd_delegate.getter  (<compiler-generated>:0)
5   custom                        0x208d9b9f8         closure #1 in UIView.hwd_didFinishDisplay()  (UIView+VAP.swift:315)

问题描述：
这个UIView的扩展是我用swift重写了，逻辑上基本一致，这个崩溃问题我理解应该是发生在多线程访问了一个已经释放的hwd_delegate。因为根据堆栈显示UIView.hwd_didFinishDisplay()发生在异步线程，可能此时hwd_delegate已经释放内存，此时访问就造成野指针。但我看到源码里所有的播放callback都是放在一个异步的队列(hwd_callbackQueue)去执行的，想问一下为什么不直接放在主队列里，而是要单独放在一个异步队列呢，是否有什么其他意图？如果我把所有的播放callback改成放在主队列里回调会有什么影响？谢谢！

补充：
这个问题仅在循环播放动画的时候遇到过。

**Comment by wubiner** [comment]
> 崩溃信息：
> OS Version: iOS 14.4.2 (18D70)
> Report Version: 104
> 
> Exception Type: EXC_BAD_ACCESS (SIGSEGV)
> Exception Codes: SEGV_NOOP
> Crashed Thread: 38
> 
> Application Specific Information:
> addObject: > countByEnumeratingWithState:objects:count: > retainWeakReference >
> Attempted to dereference garbage pointer .
> Originated at or in a subcall of unknown, cannot find symbol
> 
> 崩溃堆栈：
> Thread 38 Crashed:
> 0 libswiftCore.dylib 0x1a62a4f9c swift_getObjectType + 48
> 1 libswiftCore.dylib 0x1a5f9dad8 [inlined] $ss018_bridgeAnyObjectToB0yypyXlSgF
> 2 libswiftCore.dylib 0x1a5f9dad8 $ss018_bridgeAnyObjectToB0yypyXlSgF
> 3 custom 0x208d9cd68 UIView.hwd_delegate.getter (UIView+VAP.swift:427)
> 4 custom 0x208d9cce0 @objc UIView.hwd_delegate.getter (:0)
> 5 custom 0x208d9b9f8 closure #1 in UIView.hwd_didFinishDisplay() (UIView+VAP.swift:315)
> 
> 问题描述：
> 这个UIView的扩展是我用swift重写了，逻辑上基本一致，这个崩溃问题我理解应该是发生在多线程访问了一个已经释放的hwd_delegate。因为根据堆栈显示UIView.hwd_didFinishDisplay()发生在异步线程，可能此时hwd_delegate已经释放内存，此时访问就造成野指针。但我看到源码里所有的播放callback都是放在一个异步的队列(hwd_callbackQueue)去执行的，想问一下为什么不直接放在主队列里，而是要单独放在一个异步队列呢，是否有什么其他意图？如果我把所有的播放callback改成放在主队列里回调会有什么影响？谢谢！
> 
> 补充：
> 这个问题仅在循环播放动画的时候遇到过。

当时写这部分内容的同学已不再负责，所以无从得知设计初衷，这里猜测只是为了回调统一性，将回调都放在一个队列里。没有什么特殊原因。个人意见，callback只要不做占用主线程的事情，放在主队列也没有关系。

**Comment by borischou** [comment]
好的，我这边自测使用主队列没有什么问题，可能是担心业务调用时在主队列里使用了耗时操作阻碍了动画播放的流畅性吧。
