### ISSUE TITLE
Android版本不支持表情类文本的融合，融合后只有轮廓，iOS版则支持。

### ISSUE THREAD

**Issue by ji2ruan** [Tencent/vap#148]
表情类文本，例如😂😂😂😙😬
Android版本融合后，显示异常，只有纯色轮廓。
iOS则能正常显示。
![FB9AFB30D75C734B1484418CCFFE403E](https://user-images.githubusercontent.com/13879602/133563190-e2860196-db7d-40c5-b521-dcf188566b8a.jpg)

**Comment by hexleo** [comment]
Android又个开关，enableAutoTxtColorFill，设置为false就可以避免这个问题，但会导致文字有黑边，你可以试试
