### ISSUE TITLE
readPacketOfSample beyond bounds

### ISSUE THREAD

**Issue by Grayson2019** [Tencent/vap#153]
1. 问题描述（重现路径）首先播放一遍A动画，播放完成后触发代理viewDidFinishPlayMP4，循环播放B动画，播放一段时间（很快）动画便会卡住
2. 运行环境  iPhone7  iOS13.6
3. 相关日志 readPacketOfSample beyond bounds
4. 播放错误的文件（可选）

**Comment by wubiner** [comment]
> 1. 问题描述（重现路径）首先播放一遍A动画，播放完成后触发代理viewDidFinishPlayMP4，循环播放B动画，播放一段时间（很快）动画便会卡住
> 2. 运行环境  iPhone7  iOS13.6
> 3. 相关日志 readPacketOfSample beyond bounds
> 4. 播放错误的文件（可选）

如果是必现，麻烦贴一下素材和crash堆栈信息
