### ISSUE TITLE
同一个页面有N多个动画会不会出现消耗性能爆炸

### ISSUE THREAD

**Issue by kang558** [Tencent/vap#16]
vap是基于视频播放解码的，同一个页面有N多个动画（也就是很多个视频同时播放）会不会非常的消耗性能导致页面卡顿，有什么更好的解决方案吗？

**Comment by hexleo** [comment]
同时播放的情况：动画越多肯定越占用资源，只能人为控制同时播放动画的数量。

非同时播放的情况，不会出现过多资源占用，因为播放完成后会释放资源

并行播放目前没有什么解决方案，欢迎大家来提方案

**Comment by kang558** [comment]
这么看来，小动画不太适用，大型复杂动画比较适用

**Comment by hexleo** [comment]
一些icon的小动画确实不适合，比较大的动画，比如礼物特效这些比较合适

**Comment by karosLi** [comment]
可以提供一套缓存的方法吗，不用每次去解析，特别是统一个动画文件，在一个页面里使用会暂用多分内存

**Comment by hexleo** [comment]
因为是用MediaCodec不好做缓存，因为视频缓存也是保存nalu，不会缓存yuv数据，那数据量太大
