### ISSUE TITLE
boxDidParsed 出现了crash

### ISSUE THREAD

**Issue by bingFly** [Tencent/vap#162]
# issue 模版

1. 问题描述（重现路径）
2. 运行环境（手机型号，Android/iOS版本等）
3. 相关日志
4. 播放错误的文件（可选）
我们线上检测到crash
# issue template
![image](https://user-images.githubusercontent.com/7598300/140054141-bfe5a1bc-2804-4b84-8552-033d5ba8cda2.png)

**Comment by wubiner** [comment]
> # issue 模版
> 1. 问题描述（重现路径）
> 2. 运行环境（手机型号，Android/iOS版本等）
> 3. 相关日志
> 4. 播放错误的文件（可选）
>    我们线上检测到crash
> 
> # issue template
> ![image](https://user-images.githubusercontent.com/7598300/140054141-bfe5a1bc-2804-4b84-8552-033d5ba8cda2.png)

可以贴一下完整crash信息么

**Comment by borischou** [comment]
这个需要对二进制长度做判断保护

**Comment by borischou** [comment]
我们也遇到了，本地做了保护修复就没问题了

**Comment by hexleo** [comment]
@borischou 你们出问题的代码是哪？怎么做的保护?

**Comment by borischou** [comment]
> @borischou 你们出问题的代码是哪？怎么做的保护?

对二进制数据的长度做保护

**Comment by linjie321** [comment]
> > @borischou 你们出问题的代码是哪？怎么做的保护?
> 
> 对二进制数据的长度做保护

怎么做长度保护啊, 长度范围值是多少, 能说一下吗
