### ISSUE TITLE
Android平台存在文件句柄泄漏

### ISSUE THREAD

**Issue by pjyx** [Tencent/vap#165]
1. 问题描述（重现路径）
   重复播放/退出VAP动画的播放，文件句柄持续增加。
2. 运行环境（手机型号，Android/iOS版本等）
    华为nova5 Pro（SEA_AL10）（HarmonyOS 2.0.0）和vivo X30（Android 10）
3. 相关日志
    增加的都是anon_inode:sync_file这种类型的文件句柄。
4. 播放错误的文件（可选）
    所有VAP动画都能复现问题。

今天简单做了些对比，发现只要是 egl?.eglSwapBuffers(eglDisplay, eglSurface)函数就会泄漏，不调用这个接口文件句柄就不会持续增加。
看EGLUtil.release,该做的释放也都做了，目前没有找到解决方案，麻烦你们看下这个问题。

**Comment by hexleo** [comment]
请问你们是怎么检测句柄增加的？

**Comment by pjyx** [comment]
File fddir = new File("/proc/self/fd");
        int count = 0;
        int length = fddir.listFiles().length;
        for (File ff : fddir.listFiles()) {
          String canonicalPath = "";
          String link = "";
          try{
            canonicalPath = ff.getCanonicalPath();
            if (Build.VERSION.SDK_INT >= 21) {
              link = Os.readlink(ff.getPath());
            }

          } catch (IOException e) {
            e.printStackTrace();
          } catch (Exception e) {
            e.printStackTrace();
          }
          String line = String.format("%s -> %s -> %s\n", ff.getName(), link, canonicalPath);
          if(length - count < 30) {
            Log.i("testFd", "line:" + line);
          }
          count += 1;
        }
        Log.i("testFd", "count:" + count);

**Comment by pjyx** [comment]
@hexleo,我是用下面的方法检测文件句柄的。
File fddir = new File("/proc/self/fd");
        int count = 0;
        int length = fddir.listFiles().length;
        for (File ff : fddir.listFiles()) {
          String canonicalPath = "";
          String link = "";
          try{
            canonicalPath = ff.getCanonicalPath();
            if (Build.VERSION.SDK_INT >= 21) {
              link = Os.readlink(ff.getPath());
            }

          } catch (IOException e) {
            e.printStackTrace();
          } catch (Exception e) {
            e.printStackTrace();
          }
          String line = String.format("%s -> %s -> %s\n", ff.getName(), link, canonicalPath);
          if(length - count < 30) {
            Log.i("testFd", "line:" + line);
          }
          count += 1;
        }
        Log.i("testFd", "count:" + count);

**Comment by hexleo** [comment]
用你给的这段代码，我在小米mix3上没有出现句柄不断增加的情况，是否是特定机型才出现？eglSwapBuffers这个调用会非常频繁，每一帧都会调用，你出现句柄增多的情况，具体是什么样的（一次播放完后增加上百个句柄，还是每次播放只增加一个句柄）？

**Comment by pjyx** [comment]
我手上的两个手机都复现了，我目前看的场景都是循环播放（但测试的时候每次播放一遍都没播完），就是不停的打开
/关闭播放VAP的动画页面。一般20次会增加四五十个句柄吧。

**Comment by pjyx** [comment]
Flutter封装出现的问题，与VAP本身无关。
关闭issue。

**Comment by CuntyC** [comment]
请问可以具体说一下“Flutter封装出现的问题”嘛？我这边遇到了类似的问题

**Comment by coderloveryan** [comment]
+1 我这边也遇到了类似问题，能不能说一下具体哪里出现问题

**Comment by WATER1350** [comment]
我也遇到了，只有安卓9及以下出现了这个问题，大家后来都是怎么解决的
