### ISSUE TITLE
在recyclerview中使用的问题

### ISSUE THREAD

**Issue by xiaoanPan** [Tencent/vap#168]
在列表中使用vap时遇到两个问题：
1. recyclerview中多个item对同一个asset里的文件进行读取，大概率出现配置解析失败的问题（REPORT_ERROR_TYPE_PARSE_CONFIG），导致某些item不播放，请问有没有解决办法？
2. 每个item都有一个或者多个animView时，上下滑动非常耗内存，卡顿非常明显

**Comment by hexleo** [comment]
没有在recyclerview中使用过vap，也不建议这样用，因为textureview很消耗显存。能不能贴下日志

**Comment by xiaoanPan** [comment]
> 没有在recyclerview中使用过vap，也不建议这样用，因为textureview很消耗显存。能不能贴下日志

配置解析失败的原因定位到了，java.lang.IllegalStateException: AssetInputStream is closed，应该是多线程操作同一个asset目录下文件的问题，我尝试放到文件系统里面看看

**Comment by W-quan** [comment]
我就一个item，也是java.lang.IllegalStateException: AssetInputStream is closed
