### ISSUE TITLE
web 上连续播放，会出现上一个mp4的最后一帧残影

### ISSUE THREAD

**Issue by cc8476** [Tencent/vap#172]
1. 问题描述
播完一个Mp4之后，过1，2s继续播下一个，会闪现上一个mp4的最后一帧，然后播下一个

2. 运行环境
web chrome最新版本
npm包 0.29

3. 相关日志
播放相关代码如下
`
      function playvap(obj) {
        this.vap = new Vap(obj)
        this.vap.on('ended', () => {
            this.playing = false;
            this.vap.destroy();
            this.vap = null
            this._checkPlay();
        })
}
`

**Comment by hexleo** [comment]
@hujinliang 有空看看这个问题

**Comment by hujinliang** [comment]
我这边没出现这种情况，可以提供下代码，或者用demo看怎么复现这个问题。可以尝试在每次传的参数中设置不同的type值。
![image](https://user-images.githubusercontent.com/17648734/141418271-8f2c9cc6-da7c-4715-98b8-0bf4b23bdf25.png)

**Comment by cc8476** [comment]
感谢感谢，确实加了个type,并且设置每次type递增不会有类似情况
