### ISSUE TITLE
onFailed errorType=10005, errorMsg=0x5 parse config fail 

### ISSUE THREAD

**Issue by wuting1992** [Tencent/vap#173]
# issue 模版
解析配置错误是什么情况，这个10005的问题，

**Comment by wubiner** [comment]
> # issue 模版
> 解析配置错误是什么情况，这个10005的问题，

是安卓平台吗？是的话按照模版详细贴一下机型等信息。

**Comment by wuting1992** [comment]
1. onFailed errorType=10005, errorMsg=0x5 parse config fail
2. Android 10， HUAWEI Y9   
3. onFailed errorType=10005, errorMsg=0x5 parse config fail

**Comment by hexleo** [comment]
请提供完整的日志，10005错误表示介些vapc的配置失败，可以检查下mp4里是否携带了vapc节点

**Comment by wuting1992** [comment]
老视频兼容问题，开启兼容就行了，谢谢解答

**Comment by keke521** [comment]
> 老视频兼容问题，开启兼容就行了，谢谢解答

请问这个是怎么解决的，我华为 p30上播放本地视频文件 也遇到了这个

**Comment by hexleo** [comment]
> 10005错误表示介些vapc的配置失败，可以检查下mp4里是否携带了vapc节点

10005错误表示大部分表示vapc的配置失败，可以检查下mp4里是否携带了vapc节点，如果是老视频没有vapc节点，需要开启旧版本兼容

**Comment by 282167361** [comment]
> 

你好,请问如何开启老版本兼容

**Comment by hexleo** [comment]
> > 
> 
> 你好,请问如何开启老版本兼容

有个 enableVersion1 的接口，但不建议开启
