### ISSUE TITLE
iOS QGVAPWrapView 融合动画,播放到最后一帧的时候融合进去的图片消失了

### ISSUE THREAD

**Issue by spring321** [Tencent/vap#178]
# issue 模版

1. QGVAPWrapView 融合动画,播放到最后一帧的时候融合进去的图片消失了.
2. 设置 autoDestoryAfterFinish = false, QGVAPWrapView播放完毕,融合进去的图片也消失了

**Comment by wubiner** [comment]
> # issue 模版
> 1. QGVAPWrapView 融合动画,播放到最后一帧的时候融合进去的图片消失了.
> 2. 设置 autoDestoryAfterFinish = false, QGVAPWrapView播放完毕,融合进去的图片也消失了

麻烦附加视频看一下呢。另外是属于偶现还是必现？

**Comment by spring321** [comment]
@wubiner 这是必现的,下面这个是素材:
占位符:   "tag1"
https://user-images.githubusercontent.com/19162722/144957649-7d796b9b-c5c6-4620-b6fa-c4d5675cb912.mp4
这个是效果:
https://user-images.githubusercontent.com/19162722/144958863-791790d9-ba29-426d-b702-4835a9181386.MP4

**Comment by spring321** [comment]
@wubiner 安卓的融合动画循环播放也有这个问题(最后一针融合进去的图片丢失了),素材的帧率是60fps(素材帧率20fps没有问题), 希望安卓的这个问题也可以修复一下

**Comment by akanchi** [comment]
> https://user-images.githubusercontent.com/19162722/144957649-7d796b9b-c5c6-4620-b6fa-c4d5675cb912.mp4

这个视频有482帧，但融合信息配置只显示到481帧。所以呈现的现象是播放到最后没有融合信息。
造成这个问题的原因是ffmpeg生成视频的命令有点问题，像高一点的帧率如50、60fps视频帧数会比图片数量多1
现在生成视频的命令大致如下(使用`-r`指定帧率)：
`ffmpeg -r 24 -i "%03d.png" -pix_fmt yuv420p -vcodec libx264 -b:v 3000k -profile:v main -level 4.0 -bf 0 -bufsize 3000k -y demo.mp4`

> This is not the same as the -framerate option used for some input formats like image2 or v4l2 (it used to be the same in older versions of FFmpeg). If in doubt use -framerate instead of the input option -r.
https://ffmpeg.org/ffmpeg-all.html

ffmpeg文档说`-framerate` 和`-r`在某些输入格式的时候不是等同的，建议使用`-framerate`替换`-r`

**Comment by hexleo** [comment]
感谢反馈，我更新下工具
