### ISSUE TITLE
AnimPlayer.isStartRunning赋值问题，导致无法播放

### ISSUE THREAD

**Issue by zijinzhiyun** [Tencent/vap#180]
发现播放时AnimPlayer.isStartRunning一直为true，导致视频一直无法播放。以下代码不知道是不是引发问题的原因
AnimPlayer.startPlay会调用decoder?.prepareThread()，prepareThread()会调用createThread()，createThread()中只try了OutOfMemoryError，这时发生了其它异常，无法没办法try住，无法走到decoder?.prepareThread() == false中的isStartRunning = false逻辑，导致isStartRunning一直为true，之后就会一直无法播放了

**Comment by hexleo** [comment]
你说的这个问题是有必现路径吗？如果没有catch住的话，应该会crash才对，能提供日志吗？

**Comment by zijinzhiyun** [comment]
线上复现的，没有日志，尝试复现，没有找到必现路径。不会崩溃的，animView中调用player.startPlay()会try catch的

 override fun startPlay(fileContainer: IFileContainer) {
        ui {
            if (visibility != View.VISIBLE) {
                ALog.e(TAG, "AnimView is GONE, can't play")
                return@ui
            }
            if (!player.isRunning()) {
                lastFile = fileContainer
                player.startPlay(fileContainer)
            } else {
                ALog.e(TAG, "is running can not start")
            }
        }

**Comment by hexleo** [comment]
最外层是有try catch，我看看这个问题

**Comment by zijinzhiyun** [comment]
2021-12-07 12:03:24.096 7696-7696/  FileContainer init
2021-12-07 12:03:24.098 7696-9974/  onFrameAvailable
2021-12-07 12:03:24.098 7696-9974/  onDestroy
2021-12-07 12:03:24.100 7696-9974/  onVideoDestroy
2021-12-07 12:03:24.105 7696-9974/  parseConfig cost=3ms enableVersion1=false result=true
2021-12-07 12:03:24.105 7696-9974/  onConfigCreate
2021-12-07 12:03:24.105 7696-9974/  parse AnimConfig(version=2, totalFrames=61, width=640, height=1139, videoWidth=976, videoHeight=1152, orien=0, fps=9, isMix=false, alphaPointRect=PointRect(x=644, y=0, w=320, h=569), rgbPointRect=PointRect(x=0, y=0, w=640, h=1139), isDefaultConfig=false)
2021-12-07 12:03:24.105 7696-9974/  onDestroy
2021-12-07 12:03:24.105 7696-9974/  onVideoDestroy
2021-12-07 12:03:24.107 7696-7696/  scaleType=CENTER_CROP

这是复现的日志，没有看到onSurfaceTextureAvailable的调用，是这里的原因吗

**Comment by hexleo** [comment]
你的vap版本是多少？

**Comment by zijinzhiyun** [comment]
使用的是2.0.22版本，我会在每次onVideoComplete回调中开启新的播放文件

**Comment by zijinzhiyun** [comment]
看wiki 上写的是需要等待onComplete的回调后，才能再次调用start进行播放。这么播放会有问题吗

**Comment by hexleo** [comment]
ALog.i(TAG, "onSurfaceTextureAvailable width=$width height=$height")
这个日志有打印出来吗？

**Comment by hexleo** [comment]
onSizeChange的日志有吗？
看看这个值返回多少？怀疑是布局参数错误，导致TextureView没有回调onSurfaceTextureAvailable
![image](https://user-images.githubusercontent.com/3285051/145001484-f48b6c33-e249-4293-87f9-e17ad75380ad.png)

**Comment by zijinzhiyun** [comment]
ALog.i(TAG, "onSurfaceTextureAvailable width=$width height=$height")这个日志没有打印出来
也没有onSizeChange的日志

**Comment by zijinzhiyun** [comment]
我需要把再次播放的逻辑放到onVideoDestroy回调中吗

**Comment by hexleo** [comment]
正常在onVideoComplete就好，正常应该有onSizeChange的日志，没有这个回调是无法正常播放的，你可以确认下。我看日志你第一次应该是正常播放了才对，是第二次没有播放吧，第一次正常播放应该有onSizeChange的回调才对

**Comment by zijinzhiyun** [comment]
是的，第一次有onSizeChange回调
2021-12-07 17:33:30.529 24333-24333/com.xintiaotime.yoy E/AnimPlayer.AnimView: onAttachedToWindow
2021-12-07 17:33:30.565 24333-24333/com.xintiaotime.yoy E/AnimPlayer.AnimView: onSizeChanged w=1080, h=2244

**Comment by zijinzhiyun** [comment]
@hexleo 找到原因了
播放完成后，HardDecoder.destroyInner()方法会被HardDecoder.release和HardDecoder.destroy()调用，HardDecoder.destroyInner()会调用两次renderThread.handler?.post，handler中队列会有两条message，会执行两次onVideoDestroy()，onVideoDestroy()中又会执行AnimView.hide()，hide()中又会handler.post一个消息removeAllViews()。AnimView.prepareTextureView()会post一个prepareTextureViewRunnable，prepareTextureViewRunnable中执行addView(innerTextureView)后，刚好触发hide()中post的removeAllViews()，innerTextureView就被移除了，onSurfaceTextureAvailable()就不会被回调，就会再也不能播放了

**Comment by hexleo** [comment]
了解，我确认下问题，看如何修复

**Comment by hexleo** [comment]
你切换到这个分支 bugfix/android_destroy_inner 先验证下，我没重现你的问题，但确实会出现你说的那种情况，应该是标志位没设置正确导致。你验证没问题了我再发新版本

**Comment by zijinzhiyun** [comment]
我目前测试没有复现了

**Comment by hexleo** [comment]
在2.0.23修复了这个问题

**Comment by zijinzhiyun** [comment]
感谢
