### ISSUE TITLE
web 播放下 报错 SecurityError: The operation is insecure. 

### ISSUE THREAD

**Issue by kino0o** [Tencent/vap#185]
# issue 模版

1. Safari报错 SecurityError: The operation is insecure.
2. iOS Mac

**Comment by hujinliang** [comment]
没发现这个问题，可以参照源码src/video.ts 中创建video的代码，在浏览器中创建video，看有没有类似的问题，可能是浏览器存在什么限制

**Comment by douxingxiang** [comment]
遇到同样的问题。

场景是，mp4分发到第三方CDN，域名跟当前主域名不同，CDN的响应头Access-Control-Allow-Origin: *

**报错代码位置**
```
s.texImage2D(s.TEXTURE_2D, 0, s.RGB, s.RGB, s.UNSIGNED_BYTE, this.video);
```
**报错内容**: `SecurityError: The operation is insecure`

**系统和浏览器版本**
- Safari版本 14.1
- Macbook 版本11.0

**对照组**
- Chrome下正常（包括win和mac系统）
- mp4域名跟当前主域相同的话，可以正常播放
