### ISSUE TITLE
1.0.14版本iphone6播放视频必现闪退

### ISSUE THREAD

**Issue by Arokenda** [Tencent/vap#190]
堆栈如下
Thread 0 (crashed)  (tid = 771)
 0  libsystem_kernel.dylib!__pthread_kill + 0x8
 1  libsystem_pthread.dylib!pthread_kill$VARIANT$mp + 0x178
 2  libsystem_c.dylib!abort + 0x88
 3  libsystem_c.dylib!__assert_rtn + 0xd8
 4  Metal!MTLReportFailure + 0x20c
 5  Metal!-[_MTLCommandEncoder dealloc] + 0x84
 6  AGXMetalA8 + 0x886a8
 7  *!-[QGVAPMetalRenderer renderPixelBuffer:metalLayer:mergeInfos:] [QGVAPMetalRenderer.m:131]
 8  *!-[QGVAPMetalView display:mergeInfos:] [QGVAPMetalView.m:114]
 9  *!-[UIView(VAP) hwd_displayNext] [UIView+VAP.m:443]
10  *!__33-[UIView(VAP) hwd_renderVideoRun]_block_invoke.279 [UIView+VAP.m:399]

**Comment by wubiner** [comment]
此问题在1.0.15版本修复。麻烦更新一下版本，若问题依旧存在，请再次联系反馈

**Comment by wubiner** [comment]
此问题在1.0.16版本修复。麻烦更新一下版本，若问题依旧存在，请再次联系反馈

**Comment by rainedAllNight** [comment]
libsystem_kernel.dylib
___pthread_kill + 8
7
AGXMetalA10
0x00000001dcfaf000 + 640844
8
-[QGVAPMetalRenderer renderPixelBuffer:metalLayer:mergeInfos:] + 2212
9
-[QGVAPMetalView display:mergeInfos:] + 584
10
-[UIView(VAP) hwd_displayNext] + 536
11
___33-[UIView(VAP) hwd_renderVideoRun]_block_invoke.73 + 20

这个crash也是这个问题吗
