### ISSUE TITLE
有没有和hevc with alpha的对比的数据

### ISSUE THREAD

**Issue by cgeffect** [Tencent/vap#191]
苹果的hevc with alpha视频包含alpha通道, 内存占用和功耗方面有对比数据吗?

**Comment by wubiner** [comment]
没有测试比较过

**Comment by hexleo** [comment]
265兼容性比较差，老设备基本跑不起来，hevc with alpha是很新的特性，这个兼容性更差，估计目前没多少手机能跑起来
