### ISSUE TITLE
vap tool 2.0.6 mac 系统上生成融合mp4 失败

### ISSUE THREAD

**Issue by chenyunecjtu** [Tencent/vap#192]
[AnimTool]:start create
[CommonArgTool]:Mac OS X
[AnimTool]:createAllFrameImage
[AnimTool]:vapx error: src.id=0,src.w=0,src.h=0
[AnimTool]:Finish cost=4288

![image](https://user-images.githubusercontent.com/6322749/147816818-2a1c5eeb-8e43-4978-b9fc-ccdc1470b369.png)

**Comment by akanchi** [comment]
因为你选的mask path不对
正确的应该是`/Users/chenyun/projects/github/vap/tool/vapx_demo/mask/name`

**Comment by Shahboba** [comment]
How can I install the vap tool for Mac?
If you could send me a website of something.

**Comment by vjvj256** [comment]
VAP tool 2.0.6 تحميل

**Comment by vjvj256** [comment]
تحميل
