### ISSUE TITLE
vapc box head not found

### ISSUE THREAD

**Issue by chenyunecjtu** [Tencent/vap#193]
使用最新版本 2.0.23，使用vaptool 生成的，使用vap-player播放正常，在手机上报vapc box head not found, 从服务器拉过来的md5 和生成是一致

使用兼容老版本模式又报
AnimPlayer.AudioPlayer: cannot find audio track
 E/AnimPlayer.Decoder: onFailed errorType=10001, errorMsg=0x1 MediaExtractor exception e=java.lang.RuntimeException: No video track found

**Comment by hexleo** [comment]
是不是mp4edit无法执行的原因，你看看vaptool生成素材的时候是不是有错误日志，你可以参考FAQ 里相关解决方案https://github.com/Tencent/vap/wiki/FAQ
