### ISSUE TITLE
mp4视频推到后台再进入前台时候需要继续播放

### ISSUE THREAD

**Issue by ByronChengChen** [Tencent/vap#20]
vap 视频播放的时候，推到后台再回到前台就无法继续播放 视频了

**Comment by hexleo** [comment]
Android因为Surface会在回到桌面后被销毁，当前播放会被结束。你的问题是当前播放无法恢复，还是永远无法再播放了

**Comment by ByronChengChen** [comment]
> Android因为Surface会在回到桌面后被销毁，当前播放会被结束。你的问题是当前播放无法恢复，还是永远无法再播放了

推到后台再回到前台那个播放中的视频就停止播放了，即使我调用恢复播放方法，还是不能继续播放那个视频。

**Comment by ByronChengChen** [comment]
> Android因为Surface会在回到桌面后被销毁，当前播放会被结束。你的问题是当前播放无法恢复，还是永远无法再播放了

我还没试过重新播放是否可以。
不过我感觉应该推到后台的时候，mp4暂停播放，回到前台，mp4资源应该自动起播的。或者提供恢复方法给我们，现在我调用了恢复播放视频的方法页无法播放，只能重新播放一个新的mp4视频了。

**Comment by mlzhangyu** [comment]
iOS端现在退到后台就停止解码了 到前台以后没有恢复解码 这里我们完善优化一下

**Comment by ByronChengChen** [comment]
> iOS端现在退到后台就停止解码了 到前台以后没有恢复解码 这里我们完善优化一下

期待早日修复

**Comment by ByronChengChen** [comment]
> iOS端现在退到后台就停止解码了 到前台以后没有恢复解码 这里我们完善优化一下

期待早日优化
