### ISSUE TITLE
为什么不用AVPlayer 去实现，局限性在哪啊。

### ISSUE THREAD

**Issue by PinkJoker** [Tencent/vap#200]
用AVplayer直接进行播放获取pixelBuffer,根本还是在于着色器，这样也可以不用单独处理音视频同步，音画不同步问题，我现在采用的是AVplayer进行透明通道视频的播放，想问下Vap没有采用的原因是什么啊。

**Comment by wubiner** [comment]
这里原来做vap的时候是没有音频的，音频属于后加入功能。一开始设计vap的时候按照做播放器思路去做的，所以就没有考虑用AVplayer。对于vap其实大部分场景音画没必要严格同步，音频后期加入时，也就简单直接用系统接口了。另外，你这边基于AVplayer实现的音画同步，方便的话，可以在此问题后贴一下仓库地址，其他小伙伴有类似音画同步需求的话，可以做个参考。

**Comment by PinkJoker** [comment]
现在只是项目中自行使用，根据您的建议，后面可以把这一部分独立出来共享下

**Comment by lovesunstar** [comment]
这几天研究了下，分享一个基于 AVPlayer + VAP 的版本

https://github.com/lovesunstar/VAPAVPlayer
