### ISSUE TITLE
android.medi.MediaCodec$CodecException:Error 0xfffffc0e

### ISSUE THREAD

**Issue by Tukesboy** [Tencent/vap#202]
# issue 模版

1. 问题描述（重现路径）
 红米note9 播放出现android.medi.MediaCodec$CodecException:Error 0xfffffc0e提示报错
2. 运行环境（手机型号，Android/iOS版本等）
Android  红米note9

**Comment by hexleo** [comment]
能有更详细的日志吗？问题是否必现？

**Comment by Tukesboy** [comment]
必现的，没有详细的日志了

**Comment by Tukesboy** [comment]
MediaCodec$CodecException:start failed   OPPOreno7的手机还报这个错

**Comment by hexleo** [comment]
vap有日志接口，可以打印下vap里输出的日志信息
