### ISSUE TITLE
Android 在RecyclerView中无法播放

### ISSUE THREAD

**Issue by ji2ruan** [Tencent/vap#203]
# issue 模版

1. ViewPager内部嵌套RecyclerView，RecyclerView的adapter执行notifyDataSetChanged()，播放指定的item，无播放效果。

日志如下：
[vap_log.txt](https://github.com/Tencent/vap/files/7923988/vap_log.txt)

**Comment by ji2ruan** [comment]
使用的是最新版本

**Comment by hexleo** [comment]
你这个日志看到是有播放

**Comment by ji2ruan** [comment]
因为adapter重复刷新，play代码执行了两次，但是每次都是先停止再播放的，理论上来讲应该能播出来。
代码已经经过调整，发现还是有问题。第一次触发播放时，无法播放。
adapter刷新后，点击的item会播放一个属性动画，属性动画结束后，播放vap视频。日志如下：
![image](https://user-images.githubusercontent.com/13879602/151111803-d9c899ab-707e-46d0-b063-0c4445453cb6.png)

**Comment by hexleo** [comment]
你贴的这个错误日志，是因为view的宽高为0，导致无法播放

**Comment by ji2ruan** [comment]
我添加view时，是充满宽高添加的，不该是0啊

**Comment by ji2ruan** [comment]
好像是onSurfaceTextureAvailable这个方法没有调用~view的添加代码如下
![image](https://user-images.githubusercontent.com/13879602/151134381-b26eca21-137c-49dd-8060-8bb415945d55.png)

**Comment by ji2ruan** [comment]
看了下，好像还是onSizeChanged方法调用的问题

**Comment by hexleo** [comment]
你截图的日志大概流程是这样：
1 第一次点击视频item：
onSizeChanged没有回调，没有view的宽高信息，所以没播放，但状态标志位被记录了，只要onSizeChanged回调就会自动开始播放（但之后一直没回调）

2 第二次点击其它item：
原来的视频item onSizeChaged被回调了，因为之前记录了将要播放的状态，所以回调后会立即播放

我能想到的解决思路你可以参考下：
1 确定下为什么第一次点击没有onSizeChanged回调？因为拿不到宽高信息，所以无法播放，不清楚你那为什么没回调，可以强制刷新试试
2 看到你们使用的只是一个小icon，可以用webp替代试试，图片比较小的情况，软解webp效果也是不错的选择

**Comment by ji2ruan** [comment]
https://user-images.githubusercontent.com/13879602/151307313-5dacf1e3-b35f-4a32-a37e-0cfb240c4f16.mp4

您好，按照您的第一条思路，进行了强制刷新，onSizeChanged成功回调，onLoopStart的日志也已经在不停的打印，但是视频并没有播放，直到我拖动屏幕，onSurfaceTextureSizeChanged回调，视频才加载出来。
点击item的日志，此时无视频播放。
![image](https://user-images.githubusercontent.com/13879602/151306667-e01a1b9d-e53e-4a9f-81c1-bd4c3b69a546.png)

拖动后的日志，视频出现
![image](https://user-images.githubusercontent.com/13879602/151307084-ce19bc04-8c76-4fa8-88af-9eb55f65a0d9.png)

另外，由于用户的使用情况复杂，有时候onSizeChanged并不会回调，希望针对这种情况能优化一下，以成功播放为第一原则，必要的参数可以给予默认或者由用户传入，类似个防呆设计吧。

**Comment by hexleo** [comment]
![image](https://user-images.githubusercontent.com/3285051/151316830-cf8e90cf-4ba3-42ec-ae79-3012fa60ce59.png)
你这个时间点已经开始播放了才对，是没有图像吗？onVideoStart也回调了

onSizeChanged必须要回调才行，不然不知道如何布局，如果没有这个回调，那这个view的width 于 height 都是0，没有意义

你可以发素材给我看看，你这个素材有个异常日志，你知道是什么没解析出来吗？
![image](https://user-images.githubusercontent.com/3285051/151317135-0f580b4d-dd3c-4667-b700-4d80bfdbe2fb.png)

**Comment by ji2ruan** [comment]
那个时间点确实没有播放，或者说界面没有呈现视频播放状态
那个异常是在这发生的：
![image](https://user-images.githubusercontent.com/13879602/151320931-61a2fea7-5b5b-4adc-a085-350b1a353209.png)

我换了个素材还是有那个异常，附上素材

https://user-images.githubusercontent.com/13879602/151320983-cf5a753b-28ed-4ea9-abd4-6851e9402860.mp4

**Comment by hexleo** [comment]
你个素材我在demo里能正常播放，要不这样，你基于我们提供的demo试试，基于demo写个稳定复现的测试demo，我可以切到你的分支看看，按理说有onVideoStart应该就能播放才对

**Comment by hexleo** [comment]
你这个问题是解决了吗？你的解决方法是什么？

**Comment by D1191860939** [comment]
@ji2ruan 请问这个问题您解决了吗？您的解决方法是啥
