### ISSUE TITLE
iOS QGVAPWrapView 设置后台行为无效

### ISSUE THREAD

**Issue by AlexCzs** [Tencent/vap#207]
demo代码
`/// 使用WrapView，支持ContentMode
- (void)playVapWithWrapView {
    static BOOL pause = NO;
    QGVAPWrapView *wrapView = [[QGVAPWrapView alloc] initWithFrame:self.view.bounds];
    wrapView.center = self.view.center;
    wrapView.contentMode = QGVAPWrapViewContentModeAspectFit;
    wrapView.hwd_enterBackgroundOP = HWDMP4EBOperationTypePauseAndResume;
    wrapView.autoDestoryAfterFinish = YES;
    [self.view addSubview:wrapView];
    NSString *resPath = [NSString stringWithFormat:@"%@/Resource/vap.mp4", [[NSBundle mainBundle] resourcePath]];
    [wrapView setMute:YES];
    [wrapView playHWDMP4:resPath repeatCount:-1 delegate:self];
}`

wrapView.hwd_enterBackgroundOP = HWDMP4EBOperationTypePauseAndResume; 这句代码设置之后，App进入后台，依旧会结束播放

**Comment by AlexCzs** [comment]
修正一下，是设置后台行为，wrapView.hwd_enterBackgroundOP = HWDMP4EBOperationTypePauseAndResume

**Comment by hupengfei-hinterstellar** [comment]
你得设置wrapView里面的vapview，但外部无法访问 　╮(￣▽￣"")╭

**Comment by wubiner** [comment]
建议先采用重写一下set方法，并且在set方法调用initView方法的方式修复
