### ISSUE TITLE
ScaleType 对齐问题

### ISSUE THREAD

**Issue by Lieeber** [Tencent/vap#208]
可以顶部或底部裁剪对齐吗.

**Comment by Lieeber** [comment]
我觉得对齐特性太少了, 比如视频的宽高比大于屏幕的宽高比, 这时候如果FIT_CENTER, 由于高度不够会上下留白, 如果用CENTER_CROP又会导致宽度被裁剪 , 这时候会有底部对齐的需求. 视频宽高比小于屏幕宽高比时, 要是希望宽度适配屏幕, 使用CENTER_CROP会导致上下同时被裁剪, 现在想实现底部对齐只裁剪顶部也实现不了.

**Comment by hexleo** [comment]
留有扩展的接口，可以自己实现自定义的对齐模式
