### ISSUE TITLE
更换视频源后视频拉伸

### ISSUE THREAD

**Issue by millerzhu** [Tencent/vap#209]
1. 当播放过一个小尺寸视频（如demo里的demo.mp4）后重新new一个VideoInfo配置一个大尺寸的视频 再去播放 视频会被拉伸
  animView.enableVersion1(true)  animView.setScaleType(ScaleType.CENTER_CROP)（FIT_CENTER也是如此）
3. 运行环境 Android端

**Comment by hexleo** [comment]
能不能贴出详细的播放日志？View的大小是否有变化？
