### ISSUE TITLE
添加融合信息后会出现多余的线条或者噪点信息

### ISSUE THREAD

**Issue by jiayeah09** [Tencent/vap#21]
按照说明添加了圆形的头像跟长方形的姓名遮罩后，导出的视频遮罩区域会出现一些噪点一样在那闪动，圆形的头像区域上方也会出现一条横条。一开始以为是我切图资源问题，但是在尝试了你们提供的demo切图合成后也发现类似的情况，请问要如何修复？

![1](https://user-images.githubusercontent.com/43088064/98346489-01d35900-2051-11eb-9ea7-9700a6ee0b8c.png)
正常的

![2](https://user-images.githubusercontent.com/43088064/98346524-0a2b9400-2051-11eb-95f7-149b1ca35e93.png)
头像区域上方时不时出现线条

**Comment by hexleo** [comment]
可以把出现问题的原始图片发给我看看，也麻烦说明下具体是哪一帧会出现这样的情况。

一般出现这种问题是因为素材里会出现不透明的像素点导致

**Comment by hexleo** [comment]
github不方便发，可以加QQ群，单独qq发我 hexleo

**Comment by mlzhangyu** [comment]
这个问题我们来排查一下 查好了会在github上同步

**Comment by hexleo** [comment]
更新了Java版本的工具，可以用新工具试试
https://github.com/Tencent/vap/tree/tool2.0.0/tool

**Comment by jiayeah09** [comment]
使用java版的不会出现这个问题了，但是出现了新的问题，在添加了文字遮罩后，会在左边的视频素材上出现与遮罩大小一致的黑块
<img width="560" alt="image" src="https://user-images.githubusercontent.com/43088064/102321219-4e974180-3fb8-11eb-96bf-08491b92499e.png">

**Comment by hexleo** [comment]
tool2.0.1版本这些问题已经解决
