### ISSUE TITLE
动画不能正常播放

### ISSUE THREAD

**Issue by 846825177** [Tencent/vap#210]
# issue 模版

1. 问题描述  startPlay A->  stopPlay A-> startPlay B  ->![image](https://user-images.githubusercontent.com/31872341/157212014-5fef6df7-7a09-41aa-a7d5-ec0ee7899a0e.png) 这个地方就会给release掉
2. 运行环境（Android任意版本等）
3. 相关日志   
4. 播放错误的文件（任意）

# issue template

1. Problem description 
2. Running environment (mobile phone model, Android/iOS version, etc.)
3. Logs
4. Error file (optional)

**Comment by 846825177** [comment]
动画不能正常播放

**Comment by hexleo** [comment]
麻烦提交下日志。你是stop后直接调用start吗？正常stop后应该等待onComplete的回调后再播放，因为stop是异步的过程

**Comment by 846825177** [comment]
好的， 如果是这个原因，那我知道如何去修改自己的代码了
