### ISSUE TITLE
部分机型播放失败10002

### ISSUE THREAD

**Issue by Tukesboy** [Tencent/vap#211]
问题描述（重现路径）
   https://static.mszmapp.com/files/20210924/35cb6dcca0797a11295a94baa9aa56ae.mp4
   这个视频部分手机播放失败，视频分辨率不大 1456x1440

    运行环境（手机型号，Android/iOS版本等）

    redmi note9  4G ， 系统：Android 10

   报错10002  
   0x2 MediaCodec exception e=android.media.MediaCodec$CodecException: Error 0xfffffc0e

**Comment by hexleo** [comment]
提供下完整的播放日志

**Comment by hexleo** [comment]
建议使用最新版本的vaptool来生成动画，alpha选择0.5，看你的动画尺寸还是比较大，尽量减少尺寸吧
