### ISSUE TITLE
动画序列合成MP4之后，有黑边。播放有锯齿，web端更明显

### ISSUE THREAD

**Issue by zjions** [Tencent/vap#215]
[新建文件夹 (5).zip](https://github.com/Tencent/vap/files/8348999/5.zip)
# issue 模版

1. 问题描述（重现路径）
2. 运行环境（手机型号，Android/iOS版本等）
3. 相关日志
4. 播放错误的文件（可选）

# issue template

1. Problem description 
2. Running environment (mobile phone model, Android/iOS version, etc.)
3. Logs
4. Error file (optional)

**Comment by hexleo** [comment]
你用的工具版本发一下

**Comment by hexleo** [comment]
试了下这个素材，使用0.5 alpha 会出现黑色锯齿，你可以改为1.0 alpha大小，因为0.5确实会有损失，不同素材情况不一样，可以选择不同的alpha参数
这个是我用1.0 alpha参数生成的素材，就没有黑边了，你可以试试
https://user-images.githubusercontent.com/3285051/160093114-c5352166-9f0b-44f1-9c9d-1dd6e6071828.mp4
