### ISSUE TITLE
iOS页面切换再返回视频停止播放

### ISSUE THREAD

**Issue by GitWangKai** [Tencent/vap#217]
页面切换后，display方法执行，判断到self.window是nil，执行了 onMetalViewUnavailable 方法，将播放器 stop 了。回到视频页后，没有重启，视频停止播放了
// QGVAPMetalView.m
- (void)display:(CVPixelBufferRef)pixelBuffer mergeInfos:(NSArray<QGVAPMergedInfo *> *)infos {
    
    if (!self.window) {
        VAP_Event(kQGVAPModuleCommon, @"quit display pixelbuffer, cuz window is nil!");
        [self onMetalViewUnavailable];
        return ;
    }
    if (self.drawableSizeShouldUpdate) {
        CGFloat nativeScale = [UIScreen mainScreen].nativeScale;
        CGSize drawableSize = CGSizeMake(CGRectGetWidth(self.bounds)*nativeScale, CGRectGetHeight(self.bounds)*nativeScale);
        self.metalLayer.drawableSize = drawableSize;
        VAP_Event(kQGVAPModuleCommon, @"update drawablesize :%@", [NSValue valueWithCGSize:drawableSize]);
        self.drawableSizeShouldUpdate = NO;
    }
    [self.renderer renderPixelBuffer:pixelBuffer metalLayer:self.metalLayer mergeInfos:infos];
}

**Comment by wubiner** [comment]
这里调stop就是会停止调动画，这里表现符合预期。如果希望达到你这边预期效果，自己修改一下相关代码。
