### ISSUE TITLE
Android播放动画有淡淡的白色底

### ISSUE THREAD

**Issue by Haibeike01** [Tencent/vap#219]
在Android手机上使用demo进行播放的时候，会有白色底，这是播放的文件。 
这个mp4是UI自己用AE什么的压缩得到的，不是用系统工具弄的，但是在IOS上播放是没有这个白色底的，在安卓上播放就有这个问题。
我是用demo里的第三个按钮的案例，然后就是简单的替换下素材，把enable兼容旧版本的打开，然后播放就带有个白底，其余的demo代码没做任何修改
播放的mp4文件

https://user-images.githubusercontent.com/43381126/162969567-ce2bcade-70c2-4f1c-b764-8ae631999a21.mp4

这个是播放的动画

https://user-images.githubusercontent.com/43381126/162970423-03f40a9a-6b7b-4c47-943e-b3baf1895801.mp4

麻烦大佬看下

**Comment by hexleo** [comment]
你用AnimSimpleDemoActivity 这个demo试试，我这播放出来看着是正常的
![device-2022-04-13-093340](https://user-images.githubusercontent.com/3285051/163081570-65b08825-daca-4d5a-8eca-c8119c3f741d.png)

**Comment by hexleo** [comment]
看了下，是因为你的素材是走了老版本兼容逻辑，而你的视频分辨率 宽/高 不是16的倍数，走了一个兼容逻辑，应该是这段兼容逻辑有问题导致，我问问相同的同学。建议修改方案将视频分辨率宽高都设置为16的倍数就能解决
<img width="784" alt="image" src="https://user-images.githubusercontent.com/3285051/163083819-05de8c7a-e10b-45f7-8e6d-a320e39e3d1e.png">

**Comment by Haibeike01** [comment]
太感谢作者了，回复真及时，果然是这个问题，修改分辨率为16的倍数就解决了。
