### ISSUE TITLE
退后台后，resumeHWDMP4 动画无法恢复

### ISSUE THREAD

**Issue by fanrr** [Tencent/vap#22]

**Comment by mlzhangyu** [comment]
iOS端目前没有恢复播放的功能，后续会提供支持的，感谢提问

**Comment by lixiaonan** [comment]
> iOS端目前没有恢复播放的功能，后续会提供支持的，感谢提问

大佬你好, 这个问题有点严重啊. 在播放mp4的过程中, 甚至操作下滑出现系统的wifi、流量、亮度和声音的那个操作面板, mp4的播放都会立马暂停, 然后一直卡死在那一帧.
用户这个下滑去操作系统控制面板的情况很常见, 是经常性的, 这样的体验十分不好.

**Comment by Styx-S** [comment]
> > iOS端目前没有恢复播放的功能，后续会提供支持的，感谢提问
> 
> 大佬你好, 这个问题有点严重啊. 在播放mp4的过程中, 甚至操作下滑出现系统的wifi、流量、亮度和声音的那个操作面板, mp4的播放都会立马暂停, 然后一直卡死在那一帧.
> 用户这个下滑去操作系统控制面板的情况很常见, 是经常性的, 这样的体验十分不好.
> 不知何时能修复这个问题, 让mp4的view不再window上也能继续播放呢?

目前还不支持暂停和恢复，退后台时会立即停止播放
你的情况是停止播放后还没有移除VAP所在的view，表现出来卡死在那一帧

**Comment by lixiaonan** [comment]
> > > iOS端目前没有恢复播放的功能，后续会提供支持的，感谢提问
> > 
> > 
> > 大佬你好, 这个问题有点严重啊. 在播放mp4的过程中, 甚至操作下滑出现系统的wifi、流量、亮度和声音的那个操作面板, mp4的播放都会立马暂停, 然后一直卡死在那一帧.
> > 用户这个下滑去操作系统控制面板的情况很常见, 是经常性的, 这样的体验十分不好.
> > 不知何时能修复这个问题, 让mp4的view不再window上也能继续播放呢?
> 
> 目前还不支持暂停和恢复，退后台时会立即停止播放
> 你的情况是停止播放后还没有移除VAP所在的view，表现出来卡死在那一帧

是的, 如果下拉出现一次操作面板动画就消失了, 这样对用户体验不太好. 希望大佬们能辛苦未来优化下

**Comment by Styx-S** [comment]
> > > > iOS端目前没有恢复播放的功能，后续会提供支持的，感谢提问
> > > 
> > > 
> > > 大佬你好, 这个问题有点严重啊. 在播放mp4的过程中, 甚至操作下滑出现系统的wifi、流量、亮度和声音的那个操作面板, mp4的播放都会立马暂停, 然后一直卡死在那一帧.
> > > 用户这个下滑去操作系统控制面板的情况很常见, 是经常性的, 这样的体验十分不好.
> > > 不知何时能修复这个问题, 让mp4的view不再window上也能继续播放呢?
> > 
> > 
> > 目前还不支持暂停和恢复，退后台时会立即停止播放
> > 你的情况是停止播放后还没有移除VAP所在的view，表现出来卡死在那一帧
> 
> 是的, 如果下拉出现一次操作面板动画就消失了, 这样对用户体验不太好. 希望大佬们能辛苦未来优化下

目前没有人力来做Pause/Resume修改以及测试
如果需求比较强，你那边可以修改源码试一下：
QGMP4FrameHWDecoder中退后台时不要停止解码（需要处理回来以后可能vtsession失效的情况）
UIView+VAP中退后台时调用pauseHWDMP4，同时hwd_renderVideoRun中渲染循环改为
```
if (self.hwd_onPause) {
lastRenderingInterval = NSDate.timeIntervalSinceReferenceDate;
}
if (self.hwd_isFinish) {
break ;
}
```
由于这样修改是未经验证的，可能会有其他问题，解决并验证以后可以提PR

**Comment by lixiaonan** [comment]
> > > > > iOS端目前没有恢复播放的功能，后续会提供支持的，感谢提问
> > > > 
> > > > 
> > > > 大佬你好, 这个问题有点严重啊. 在播放mp4的过程中, 甚至操作下滑出现系统的wifi、流量、亮度和声音的那个操作面板, mp4的播放都会立马暂停, 然后一直卡死在那一帧.
> > > > 用户这个下滑去操作系统控制面板的情况很常见, 是经常性的, 这样的体验十分不好.
> > > > 不知何时能修复这个问题, 让mp4的view不再window上也能继续播放呢?
> > > 
> > > 
> > > 目前还不支持暂停和恢复，退后台时会立即停止播放
> > > 你的情况是停止播放后还没有移除VAP所在的view，表现出来卡死在那一帧
> > 
> > 
> > 是的, 如果下拉出现一次操作面板动画就消失了, 这样对用户体验不太好. 希望大佬们能辛苦未来优化下
> 
> 目前没有人力来做Pause/Resume修改以及测试
> 如果需求比较强，你那边可以修改源码试一下：
> QGMP4FrameHWDecoder中退后台时不要停止解码（需要处理回来以后可能vtsession失效的情况）
> UIView+VAP中退后台时调用pauseHWDMP4，同时hwd_renderVideoRun中渲染循环改为
> 
> ```
> if (self.hwd_onPause) {
> lastRenderingInterval = NSDate.timeIntervalSinceReferenceDate;
> }
> if (self.hwd_isFinish) {
> break ;
> }
> ```
> 
> 由于这样修改是未经验证的，可能会有其他问题，解决并验证以后可以提PR

好的, 谢谢您

**Comment by unknowntc** [comment]
> QGMP4FrameHWDecoder中退后台时不要停止解码（需要处理回来以后可能vtsession失效的情况）

QGMP4FrameHWDecoder中退后台时不要停止解码（需要处理回来以后可能vtsession失效的情况）请问这个怎么设置

**Comment by unknowntc** [comment]
> > > > > iOS端目前没有恢复播放的功能，后续会提供支持的，感谢提问
> > > > 
> > > > 
> > > > 大佬你好, 这个问题有点严重啊. 在播放mp4的过程中, 甚至操作下滑出现系统的wifi、流量、亮度和声音的那个操作面板, mp4的播放都会立马暂停, 然后一直卡死在那一帧.
> > > > 用户这个下滑去操作系统控制面板的情况很常见, 是经常性的, 这样的体验十分不好.
> > > > 不知何时能修复这个问题, 让mp4的view不再window上也能继续播放呢?
> > > 
> > > 
> > > 目前还不支持暂停和恢复，退后台时会立即停止播放
> > > 你的情况是停止播放后还没有移除VAP所在的view，表现出来卡死在那一帧
> > 
> > 
> > 是的, 如果下拉出现一次操作面板动画就消失了, 这样对用户体验不太好. 希望大佬们能辛苦未来优化下
> 
> 目前没有人力来做Pause/Resume修改以及测试
> 如果需求比较强，你那边可以修改源码试一下：
> QGMP4FrameHWDecoder中退后台时不要停止解码（需要处理回来以后可能vtsession失效的情况）
> UIView+VAP中退后台时调用pauseHWDMP4，同时hwd_renderVideoRun中渲染循环改为
> 
> ```
> if (self.hwd_onPause) {
> lastRenderingInterval = NSDate.timeIntervalSinceReferenceDate;
> }
> if (self.hwd_isFinish) {
> break ;
> }
> ```
> 
> 由于这样修改是未经验证的，可能会有其他问题，解决并验证以后可以提PR



> > > > > iOS端目前没有恢复播放的功能，后续会提供支持的，感谢提问
> > > > 
> > > > 
> > > > 大佬你好, 这个问题有点严重啊. 在播放mp4的过程中, 甚至操作下滑出现系统的wifi、流量、亮度和声音的那个操作面板, mp4的播放都会立马暂停, 然后一直卡死在那一帧.
> > > > 用户这个下滑去操作系统控制面板的情况很常见, 是经常性的, 这样的体验十分不好.
> > > > 不知何时能修复这个问题, 让mp4的view不再window上也能继续播放呢?
> > > 
> > > 
> > > 目前还不支持暂停和恢复，退后台时会立即停止播放
> > > 你的情况是停止播放后还没有移除VAP所在的view，表现出来卡死在那一帧
> > 
> > 
> > 是的, 如果下拉出现一次操作面板动画就消失了, 这样对用户体验不太好. 希望大佬们能辛苦未来优化下
> 
> 目前没有人力来做Pause/Resume修改以及测试
> 如果需求比较强，你那边可以修改源码试一下：
> QGMP4FrameHWDecoder中退后台时不要停止解码（需要处理回来以后可能vtsession失效的情况）
> UIView+VAP中退后台时调用pauseHWDMP4，同时hwd_renderVideoRun中渲染循环改为
> 
> ```
> if (self.hwd_onPause) {
> lastRenderingInterval = NSDate.timeIntervalSinceReferenceDate;
> }
> if (self.hwd_isFinish) {
> break ;
> }
> ```
> 
> 由于这样修改是未经验证的，可能会有其他问题，解决并验证以后可以提PR

QGMP4FrameHWDecoder中退后台时不要停止解码（需要处理回来以后可能vtsession失效的情况）请问这个怎么设置
