### ISSUE TITLE
iOS Release模式下 内存暴涨 导致Crash

### ISSUE THREAD

**Issue by DavidCap** [Tencent/vap#220]
# issue 模版

1. 问题描述（重现路径）
Debug模式下播放素材没有问题，Rlease模式下播放素材导致内存暴涨 Crash。

3. 运行环境（手机型号，Android/iOS版本等）
iOS 版本：15.1
SDK版本：1.0.6

4. 相关日志
Demo的地址：https://github.com/DavidCap/VapDemo
Demo就是github上的project，替换了素材

下载demo，xcode记得变成Rlease模式下run起来，点击 “电竞方案（退后台结束）”，内存就会暴涨 最终crash

5. 播放错误的文件（可选）

**Comment by DavidCap** [comment]
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/5005468/163124190-41b36c33-d51c-4420-904a-5eb4a562e487.png">
附上内存 暴涨的图片

**Comment by wubiner** [comment]
属于非vap工具制作的素材，无法兼容，建议使用vap配套工具重新生成素材

**Comment by wubiner** [comment]
已在iOS1.0.17版本处理
