### ISSUE TITLE
QGMP4Parser.readBoxTypeAndLength的length为0导致parse会死循环

### ISSUE THREAD

**Issue by ryanzhuang** [Tencent/vap#222]
# issue 模版

1. 问题描述（重现路径）
2. 运行环境（iOS）
3. 相关日志
4. 播放错误的文件（可选）

# issue template

1. Problem description 
2. Running environment (mobile phone model, Android/iOS version, etc.)
3. Logs
4. Error file (optional)

**Comment by wubiner** [comment]
这部分解析逻辑兼容性确实不足，后期计划重构解析部分。

**Comment by wubiner** [comment]
已在iOS1.0.17版本处理
