### ISSUE TITLE
android 10 many similar crashes

### ISSUE THREAD

**Issue by smalldayday** [Tencent/vap#223]
# issue 模版

1. 问题描述  超级多的崩溃
2. 运行环境
  SDK  api "io.github.tencent:vap:2.0.20" // VAP mp4 动画
  Android 10 Samsung Galaxy A02s、Samsung Galaxy J6+、Redmi 8A、Samsung Galaxy A6+、Xiaomi Redmi 7A、Samsung Galaxy J8、
Samsung Galaxy A11、Redmi 8A Dual
3. 相关日志
backtrace:
  #00  pc 00000000000604ee  /apex/com.android.runtime/lib/bionic/libc.so (abort+166)
  #00  pc 0000000000005aad  /system/lib/liblog.so (__android_log_assert+176)
  #00  pc 00000000001f5c8f  /system/lib/libhwui.so (android::uirenderer::skiapipeline::SkiaOpenGLPipeline::swapBuffers(android::uirenderer::renderthread::Frame const&, bool, SkRect const&, android::uirenderer::FrameInfo*, bool*)+94)
  #00  pc 00000000001f4e65  /system/lib/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw()+356)
  #00  pc 00000000001f43c1  /system/lib/libhwui.so (android::uirenderer::renderthread::DrawFrameTask::run()+156)
  #00  pc 0000000000202579  /system/lib/libhwui.so (android::uirenderer::WorkQueue::process()+164)
  #00  pc 00000000002023d1  /system/lib/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+72)
  #00  pc 000000000000da57  /system/lib/libutils.so (android::Thread::_threadLoop(void*)+214)
  #00  pc 00000000000aa8bb  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+20)
  #00  pc 0000000000061993  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30)

**Comment by smalldayday** [comment]
![image](https://user-images.githubusercontent.com/46509783/166859786-3f8858dd-8bae-4a2a-9a9c-7f182419bef2.png)
backtrace:
  #00  pc 000000000005f356  /apex/com.android.runtime/lib/bionic/libc.so (abort+166)
  #00  pc 0000000000005a31  /system/lib/liblog.so (__android_log_assert+176)
  #00  pc 000000000029f6cf  /system/lib/libhwui.so (android::uirenderer::skiapipeline::SkiaOpenGLPipeline::swapBuffers(android::uirenderer::renderthread::Frame const&, bool, SkRect const&, android::uirenderer::FrameInfo*, bool*)+94)
  #00  pc 00000000002a4bef  /system/lib/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw()+362)
  #00  pc 00000000002a414b  /system/lib/libhwui.so (_ZNSt3__110__function6__funcIZN7android10uirenderer12renderthread13DrawFrameTask11postAndWaitEvE3$_0NS_9allocatorIS6_EEFvvEEclEv$c303f2d2360db58ed70a2d0ac7ed911b+170)
  #00  pc 00000000002b1aef  /system/lib/libhwui.so (android::uirenderer::WorkQueue::process()+158)
  #00  pc 00000000002b194d  /system/lib/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+72)
  #00  pc 000000000000d8b3  /system/lib/libutils.so (android::Thread::_threadLoop(void*)+182)
  #00  pc 00000000000a6293  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+20)
  #00  pc 0000000000060803  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30)

**Comment by smalldayday** [comment]
![image](https://user-images.githubusercontent.com/46509783/166859844-ee9943ff-fcde-4be3-8f38-80352be2a83d.png)
backtrace:
  #00  pc 00000000000604ee  /apex/com.android.runtime/lib/bionic/libc.so (abort+166)
  #00  pc 0000000000005aad  /system/lib/liblog.so (__android_log_assert+176)
  #00  pc 00000000001f5c8f  /system/lib/libhwui.so (android::uirenderer::skiapipeline::SkiaOpenGLPipeline::swapBuffers(android::uirenderer::renderthread::Frame const&, bool, SkRect const&, android::uirenderer::FrameInfo*, bool*)+94)
  #00  pc 00000000001f4e65  /system/lib/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw()+356)
  #00  pc 00000000001f43c1  /system/lib/libhwui.so (android::uirenderer::renderthread::DrawFrameTask::run()+156)
  #00  pc 0000000000202579  /system/lib/libhwui.so (android::uirenderer::WorkQueue::process()+164)
  #00  pc 00000000002023d1  /system/lib/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+72)
  #00  pc 000000000000da57  /system/lib/libutils.so (android::Thread::_threadLoop(void*)+214)
  #00  pc 00000000000aa8bb  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+20)
  #00  pc 0000000000061993  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30)

**Comment by hexleo** [comment]
使用TextureView实现openGL确实会有crash，但crash率能控制在0.1%左右，你统计的crash率有多少？还有，从堆栈里看没看出一定是vap导致，你是单独测试的vap demo吗？

**Comment by smalldayday** [comment]
> 使用TextureView实现openGL确实会有crash，但crash率能控制在0.1%左右，你统计的crash率有多少？还有，从堆栈里看没看出一定是vap导致，你是单独测试的vap demo吗？

不是单独测试的VAP Demo 线上收集到的日志，全局搜索了下 仅有VAP SDK有renderthread

**Comment by hexleo** [comment]
renderthread 是Android的系统渲染线程，不是vap创建的线程
