### ISSUE TITLE
素材制作工具出错

### ISSUE THREAD

**Issue by zldesigner** [Tencent/vap#224]
[ToolUI]:VAP tool 2.0.6
[ToolUI]:CommonArg{ffmpegCmd='ffmpeg', mp4editCmd='mp4edit', enableH265=false, fps=25, enableCrf=false, bitrate=2000, crf=29, scale=0.5, inputPath='/Users/zhaoliang/K bean', needAudio=false', audioPath='null'}
[AnimTool]:start create
[CommonArgTool]:Mac OS X
[AnimTool]:createAllFrameImage
[AnimTool]:{"info":{"v":2,"f":30,"w":720,"h":404,"fps":25,"videoW":720,"videoH":624,"aFrame":[0,408,360,202],"rgbFrame":[0,0,720,404],"isVapx":0,"orien":0}}
[AnimTool]:run createMp4
[AnimTool]:Error:createVideo error:Cannot run program "ffmpeg": error=2, No such file or directory
[AnimTool]:Finish cost=1240

**Comment by hexleo** [comment]
createVideo error:Cannot run program "ffmpeg": error=2, No such file or directory

无法运行ffmpeg程序导致，你先检查下 mac 目录下的ffmpeg与mp4edit这两个程序能否正常运行，检查方式参考文档 https://github.com/Tencent/vap/tree/master/tool
