### ISSUE TITLE
Android端使用vap动画使用DrawingCache截出来是一片空白，请问有解决的办法吗

### ISSUE THREAD

**Issue by yaoranzjy** [Tencent/vap#227]
代码如下：
getWindow().getDecorView().setDrawingCacheEnabled(true);
Bitmap bitmap = Bitmap.createBitmap(getWindow().getDecorView().getDrawingCache());
getWindow().getDecorView().setDrawingCacheEnabled(false);
屏幕上的其它控件是可以这样截下来的，动画部分是空白的

**Comment by hexleo** [comment]
DrawingCache 是软绘制的开关，VAP是OpengGL绘制到surfaceTexture上，属于硬件绘制，所以DrawingCache截取不到图片。

如果你想截图，可以使用OpenGL指令到处缓存buffer或fbo，系统api的话可以调用 PixelCopy（ sdk >= 24）
