### ISSUE TITLE
同时依赖 QGVAPlayer  1.0.17 版本 和 GPUImage ，编译出错

### ISSUE THREAD

**Issue by antonynz** [Tencent/vap#229]
1. 问题描述（重现路径）
同时依赖 QGVAPlayer  1.0.17 版本 和 GPUImage ，编译出错，错误信息是 _kColorConversion601FullRange 符号重复

2. 运行环境（手机型号，Android/iOS版本等）
iOS 平台

3. 相关日志
duplicate symbol '_kColorConversion601FullRange' in:
    /Users/xxx/Library/Developer/Xcode/DerivedData/Runner-cskjyxivnuuncdeeqmishasyltxi/Build/Products/Debug-iphoneos/GPUImage/GPUImage.framework/GPUImage(GPUImageVideoCamera.o)
    /Users/xxx/Library/Developer/Xcode/DerivedData/Runner-cskjyxivnuuncdeeqmishasyltxi/Build/Products/Debug-iphoneos/QGVAPlayer/QGVAPlayer.framework/QGVAPlayer(QGHWDMP4OpenGLView.o)
ld: 1 duplicate symbol for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by wubiner** [comment]
着急的话，自己改一下命名吧，我这边之后统一加前缀避免一下符号冲突。
