### ISSUE TITLE
iOS 模拟器无法播放

### ISSUE THREAD

**Issue by BigQiangg** [Tencent/vap#23]
iOS 模拟器无法播放，需要额外配置么

**Comment by BigQiangg** [comment]
if ([[UIDevice currentDevice] hwd_isSimulator]) {
        VAP_Error(kQGVAPModuleCommon, @"playHWDMP4 error! not allowed in Simulator!");
        [self stopHWDMP4];
        return ;
    }

**Comment by mlzhangyu** [comment]
目前还不支持模拟器播放，后续会提供支持
