### ISSUE TITLE
加载融合图片卡死

### ISSUE THREAD

**Issue by Arokenda** [Tencent/vap#231]
问题：iOS平台偶现加载融合图片时卡死。未知何资源引起，非必现

 1  libdispatch.dylib!_dispatch_sema4_wait + 0x18
 2  libdispatch.dylib!_dispatch_semaphore_wait_slow + 0x80
 3  MetalKit!-[MTKTextureLoader newTextureWithCGImage:options:error:] + 0x118
 4 ****!+[QGVAPTextureLoader loadTextureWithImage:device:] [QGVAPTextureLoader.m:52]
 5  ****!__38-[QGVAPConfigManager loadMTLTextures:]_block_invoke [QGVAPConfigManager.m:117]
 6  CoreFoundation!__NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__ + 0x14
 7  CoreFoundation!-[__NSArrayI_Transfer enumerateObjectsWithOptions:usingBlock:] + 0x9c
 8  ****!-[QGVAPConfigManager loadMTLTextures:] [QGVAPConfigManager.m:116]
 9  ****!-[UIView(VAP) hwd_loadMetalDataIfNeed] [UIView+VAP.m:226]
10  ****!-[UIView(VAP) onVAPConfigResourcesLoaded:error:] [UIView+VAP.m:545]
11  ****!__41-[QGVAPConfigManager loadConfigResources]_block_invoke.83 [QGVAPConfigManager.m:109]
12  libdispatch.dylib!_dispatch_call_block_and_release + 0x1c
13  libdispatch.dylib!_dispatch_client_callout + 0x10
14  libdispatch.dylib!_dispatch_main_queue_drain + 0x39c
15  libdispatch.dylib!_dispatch_main_queue_callback_4CF + 0x28
16  CoreFoundation!__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 0xc
17  CoreFoundation!__CFRunLoopRun + 0x9e0
18  CoreFoundation!CFRunLoopRunSpecific + 0x254
19  GraphicsServices!GSEventRunModal + 0xa0
20  UIKitCore!-[UIApplication _run] + 0x448
21  UIKitCore!UIApplicationMain + 0x168
22  ****!main [main.mm:88]
23  ****!ProtocolConformancesSection + 0xd5003a

**Comment by Arokenda** [comment]
https://user-images.githubusercontent.com/7910601/172548813-02852e71-d76f-49bd-97e9-4b0d35810623.mp4

找到一份卡死日志最后播放的是这个视频，vap版本号为：1.0.16

**Comment by wubiner** [comment]
这个问题应该和视频没有关系，可能是与你们用的图片素材有关，可以检查一下图片素材格式以及大小，有没有异常。
