### ISSUE TITLE
在 podspec 中指定 Metal 依赖

### ISSUE THREAD

**Issue by Navimark** [Tencent/vap#233]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

请求在 `.podspec` 中添加对 `Metal` 和 `MetalKit` 的依赖（如下），虽然在主工程也可以手动添加这些 framework，但不够内聚。
```ruby
  spec.frameworks = "Metal", "MetalKit"
```

**Comment by wubiner** [comment]
ios1.0.18已修复
