### ISSUE TITLE
默认配置播放时，渲染不一致

### ISSUE THREAD

**Issue by lzb6666** [Tencent/vap#234]
1. 问题描述（重现路径）：附件资源是不包含vapc的MP4文件，使用默认version1的左alpha右rgb的方式播放；按照我的理解，左边黑色表示alpha为0，右边对应的图像将不会呈现；实际播放时发现在不同的背景下渲染结果不同。如果使用纯白色作为背景，视频中H265的字样不会被显示出来，使用其他颜色时则会显示（通过改变activity_anim_simple_demo.xml中根布局FrameLayout的背景色）。
我理解这应该是不符合预期的？实际效果如图：
![image](https://user-images.githubusercontent.com/31194937/170961751-6fd01c7f-32ed-459d-a882-23f2f45183a9.png)
![image](https://user-images.githubusercontent.com/31194937/170961843-cad077db-0df5-4684-b42a-8611a29448ba.png)

2. 运行环境 目前未发现设备相关性，手边的测试机是Android 9 10 11的，可以出现

https://user-images.githubusercontent.com/31194937/170960304-689317b4-26f4-4ff8-b107-a5d62d3fc99c.mp4

**Comment by hexleo** [comment]
你看看这个issue能不能解决你的问题

**Comment by lzb6666** [comment]
> 你看看这个issue能不能解决你的问题 #219

![image](https://user-images.githubusercontent.com/31194937/170990679-7646a022-5f43-4178-98b0-cb31956efe26.png)
应该不是16倍数的问题，这里视频尺寸是16的倍数,我之前有debug没有走YUVRender；顺便说下，视频是工具导出的H264，上面的“H265”文字，是用ffmpeg转换成H265时加的文字，用来测试时标记264 265用的

**Comment by hexleo** [comment]
你传的mp4文件不能下载，再传一份我看看

**Comment by lzb6666** [comment]
[1MrPZB.zip](https://github.com/Tencent/vap/files/8801430/1MrPZB.zip)
上面应该是因为是265所以不能直接播放，这个压缩成zip了

**Comment by hexleo** [comment]
我试了下，问题应该还是出现在glBlend设置的问题，可以参考这个issue

**Comment by lzb6666** [comment]
我试验了下，可能不是vap的原因。我通过TextureView#getBitmap的Api拿到当前渲染画面的bitmap，将它设置到一个ImageView当中，如果这个ImageView背景是黑色背景，那么这个bitmap就会被渲染出来，如果是白色背景则不会。整体表现和AnimView一致。
布局：
`    <com.tencent.qgame.animplayer.AnimView
        android:id="@+id/playerView"
        android:layout_width="300dp"
        android:layout_height="300dp"
        android:layout_gravity="center" />


    <ImageView
        android:id="@+id/preview"
        android:layout_width="200dp"
        android:layout_height="200dp"
        android:background="#000000" />`
渲染：
强制设置了alpha为0
`gl_FragColor = vec4(rgbColor.r, rgbColor.g, rgbColor.b, 0);`
`        animView.getBitmap()?.let {
            preview.post {
                preview.setImageBitmap(it)
            }
        }`
ImageView黑色背景效果：
![image](https://user-images.githubusercontent.com/31194937/171126479-45db3d82-4f80-468e-a68b-6003fd5c4e89.png)
ImageView白色背景效果：
![image](https://user-images.githubusercontent.com/31194937/171126887-7d86e773-86e8-400d-b424-d83e4c41ddca.png)
整体设置黑色背景效果：
![image](https://user-images.githubusercontent.com/31194937/171127034-01424906-a0d8-4117-9dd3-e779b80a86d5.png)

**Comment by hexleo** [comment]
你说的这个情况不是很清楚，但通过设置glBlend参数是能解决之前的问题

**Comment by lzb6666** [comment]
试了下，我想应该是弄清楚了。应该是默认的合成方式会导致即使alpha为0，但是在某些背景下仍会显示。这一点可以通过上面从TextureView直接拿bitmap设置到ImageView也会展示证明。如果渲染视频时指定
