### ISSUE TITLE
Android 播放完成后停留在最后一帧

### ISSUE THREAD

**Issue by dunzhixuan** [Tencent/vap#236]
请问有没有这个需求的规划啊，这个还是一个挺需要的功能

**Comment by hexleo** [comment]
现在没人力来支持这个特性

**Comment by lzb6666** [comment]
> 现在没人力来支持这个特性

最简单的实现，只要播放完毕不clear就好，decoder等可以正常release，本地实现了下。或者我晚点提个pr看看？

**Comment by hexleo** [comment]
我们之前试过，会有兼容问题。在某些交互简单的场景你可以这样做，但我不会合入主干，修改后你可以打包自己的sdk

**Comment by lzb6666** [comment]
> 我们之前试过，会有兼容问题。在某些交互简单的场景你可以这样做，但我不会合入主干，修改后你可以打包自己的sdk

明白了 我再研究研究
