### ISSUE TITLE
动画播放一遍后，需要seekTo到指定时间点，进行循环播放

### ISSUE THREAD

**Issue by jveryspace** [Tencent/vap#238]
android端可以提供一个实现思路吗？谢谢

**Comment by hexleo** [comment]
可以在MediaCodec解码的时候，设置不让其上屏渲染就好，正常解码到需要播放的帧，再设置上屏渲染

**Comment by jveryspace** [comment]
@hexleo 你好，[上面的方法](https://github.com/Tencent/vap/issues/238#issuecomment-1155889430) 确实可以循环播放，同时发现一个问题，我这里frameIndex > 73 之后需要重读播放，
val doRender = !outputDone && frameIndex >= 73
if (doRender) {
    speedControlUtil.preRender(bufferInfo.presentationTimeUs)
}
这里如果缓冲区里的可展示时间>当前视频播放的总时间，就休眠一下，展示当前的帧，结果就会出现每次循环中间出现一段时间的停顿。
大佬，可以再提供一下解决思路吗？谢谢

**Comment by hexleo** [comment]
没很明白你的具体问题。主体思路是通过快速解码（不上屏，只解码）到达你想要播放的那一帧。中间“快速解码”这个过程不一定很快，如果帧数比较多的话，是会出现“卡顿”这种情况

**Comment by jveryspace** [comment]
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/93655716/173786763-789bd7fd-78e6-4079-8c07-f6442df58700.png">这部分是快速解码的过程吗？
前面73帧“快速解码”不上屏，确实出现“卡顿”了
我在其他地方看到，可以通过extractor.advance() * 73 次，跳过73帧，但是循环播放的那部分会花，是不是可以通过VapTool 设置额外的关键帧，可以避免循环播放的部分变花？

**Comment by hexleo** [comment]
不能直接跳到某一帧，跳帧只能跳“关键帧”，不然就会解码花屏。目前没有“关键帧”这个信息，所以建议从头开始就好。快速解码就是只鹅解码，在releaseOutputBuffer的时候不上屏（render参数为false），也不sleep

**Comment by jveryspace** [comment]
@hexleo 谢谢
