### ISSUE TITLE
模拟器无法加载动画，demo也不行

### ISSUE THREAD

**Issue by l476175728** [Tencent/vap#240]
# issue 模版

1. 问题描述  用户使用网易mumu出的模拟器 androidX版本，播放vap动画时无法播放
2. 运行环境  android mumu 模拟器 
3. Demo也无法播放
4.  A TextureView or a subclass can only be used with hardware acceleration enabled  报的这个错，这个模拟器不支持硬件加速

**Comment by hexleo** [comment]
因为使用硬件解码能力，所以不保证模拟器能正常运行
