### ISSUE TITLE
首次播放后,再次播放无效果,上一次播放的onVideoComplete已执行

### ISSUE THREAD

**Issue by pmzcnmb1** [Tencent/vap#241]
1. 首次播放后,第二次播放无法正常播放,上一次播放的onVideoComplete已执行,第三次调用播放则日志出现is running can not start
2. iqoo neo05
3. 
[errlog_vap_0628.txt](https://github.com/Tencent/vap/files/8999695/errlog_vap_0628.txt)

https://user-images.githubusercontent.com/7694800/176146247-1c530b10-b30e-4a42-bb67-d9309a2698a7.mp4

4.

**Comment by pmzcnmb1** [comment]
vap sdk版本 2.0.25

**Comment by pmzcnmb1** [comment]
翻阅了vap相关的issue 看到您这边提醒的是onComplete回调才能调用startPlay,我这边也的确是在onVideoComplete->onVideoDestroy后再次调用播放的  楼上日志有明细

**Comment by pmzcnmb1** [comment]
线程问题,已解决

**Comment by JungleJie** [comment]
请问下楼主怎么保证切换播放源在onVideoComplete->onVideoDestroy后再次调用播放
