### ISSUE TITLE
如何获取播放后的每一帧图片呢？有这种方法吗？

### ISSUE THREAD

**Issue by chaozhouzhang** [Tencent/vap#242]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hexleo** [comment]
Android 有个PixelCopy 工具可以试试，但效率非常低

**Comment by chaozhouzhang** [comment]
试了一下，PixelCopy获取到的每一帧都是都黑底的，透明度没有了。

**Comment by chaozhouzhang** [comment]
> Android 有个PixelCopy 工具可以试试，但效率非常低

试了一下，PixelCopy获取到的每一帧都是都黑底的，透明度没有了。

**Comment by chaozhouzhang** [comment]
> Android 有个PixelCopy 工具可以试试，但效率非常低

`            @RequiresApi(Build.VERSION_CODES.N)
            override fun onVideoRender(frameIndex: Int, config: AnimConfig?) {
                val bitmap = Bitmap.createBitmap(
                    this@HsingVapView.width,
                    this@HsingVapView.height,
                    Bitmap.Config.ARGB_8888
                )
                bitmap.eraseColor(Color.WHITE)
                val surface = Surface(getSurfaceTexture())
                PixelCopy.request(
                    surface, bitmap,
                    {
                        val curr = frameIndex.toString()
                        val origin = StringBuffer("0000")
                        val start = origin.length - curr.length
                        val result = origin.replace(start, start + curr.length, curr)
                        val file = File(FileUtil.svgaFramePath(), "${result}.png")
                        FileUtil.saveBitmapToFile(file, bitmap)
                    }, Handler(Looper.getMainLooper())
                )
            }`

**Comment by hexleo** [comment]
这个需要你自己再调试了，AnimView是透明的。VAP不提供截图能力
