### ISSUE TITLE
可以支持播放网络文件吗？

### ISSUE THREAD

**Issue by symjdk** [Tencent/vap#25]

**Comment by hexleo** [comment]
目前只支持下载完成后播放，因为在线播放有两个问题：1） 文件校验不好做；2）vap主要还是播放短小的视频，网络下载导致卡顿效果差，不好处理

**Comment by CaptainHuangsh** [comment]
gif实际也是下载后才播放的；如果支持网络播放；类似gif这样先展示第一帧，下载好后再播放，理论上效果是会优于gif的吧（按照文档说的体积小于同等效果的gif）

**Comment by hexleo** [comment]
如果之前讲的两个问题不在乎的话，其实是可以支持，但改动会比较大，目前没有计划支持。简单的下载封装大家可以做个vap的插件支持，欢迎提pr。
