### ISSUE TITLE
安卓音频循环不能正常工作

### ISSUE THREAD

**Issue by nabe1005** [Tencent/vap#250]
# 安卓音频循环不能正常工作

1. 问题描述（重现路径）
    - 音频的循环播放不能正确执行
    - 在循环播放期间，视频和音频不能以正确的时间播放  

2. 运行环境（手机型号，Android/iOS版本等）
    - Android 12, Pixel 5a

## 音频的循环播放不能正确执行

animView的setLoop中指定的循环设置没有被正确反映。

当在animPlayer中为playLoop设置一个值时，同样的值会反映在audioPlayer中的playLoop中，但循环数可能无法正确确定，因为在确定音频循环时，循环数被进一步减去了。

在我的环境中，animPlayer的playLoop更新速度比audioPlayer快，所以我能够通过移除audioPlayer的循环决定的递减来获得正确的循环决定。
这是一个正确的修复方法吗？

https://github.com/Tencent/vap/blob/114905a229e3542a4e73ce5be4e29e4baa223f5f/Android/PlayerProj/animplayer/src/main/java/com/tencent/qgame/animplayer/AudioPlayer.kt#L141

## 在循环播放期间，视频和音频不能以正确的时间播放  

在循环播放期间，视频在音频之前播放。 因此，在每个循环中，视频和音频是不同步的。

在iOS上，视频可以在循环过程中同时播放，这一点能否得到纠正，以便在Android上也能同时播放？

**Comment by hexleo** [comment]
Android没有专门做音画同步，所以在多次loop后音话不同步的感觉会跟差。
解决方法：1 保证视频播放时长和音频播放时长相同（这个是兼容做法）
2 需要修改代码，视频播放完成后音频也要同步结束，开始新的loop时再重启音频播放（这个目前没有人力，等有空我再看看这块内容）
