### ISSUE TITLE
android崩溃问题

### ISSUE THREAD

**Issue by xiaoanPan** [Tencent/vap#251]
问题描述：
    bugly上发现多个崩溃日志，无法确认具体场景；
发生问题设备：
    多为三星设备，android版本多为6.0
部分崩溃日志：
![image](https://user-images.githubusercontent.com/16420863/180711608-322ea7cf-6d49-499f-890e-3f402a43d948.png)
![image](https://user-images.githubusercontent.com/16420863/180711686-8f189d8d-63da-4122-a90e-bc0d0fdf84fe.png)

**Comment by hexleo** [comment]
读取 Assets 的文件有兼容问题，建议从asset拷贝出来后用file的接口进行播放
