### ISSUE TITLE
iOS偶现闪退

### ISSUE THREAD

**Issue by fuchenxi** [Tencent/vap#253]
1. 问题描述
    目前还无法重现，线上抓取的Crash日志
2. 运行环境
     iPhone8 
     15.4.1 
     未越狱 
     竖屏  
     可用RAM：54.14MB
     可用磁盘：207.5GB
3. 日志
```
Crashed: com.apple.main-thread
0  libobjc.A.dylib                0xf74c AutoreleasePoolPage::AutoreleasePoolPage(AutoreleasePoolPage*) + 80
1  libobjc.A.dylib                0x13cac AutoreleasePoolPage::autoreleaseFullPage(objc_object*, AutoreleasePoolPage*) + 60
2  libobjc.A.dylib                0x2a90 objc_object::rootAutorelease2() + 104
3  QGVAPlayer                     0x12098 dataConvertToUInt64 + 48
4  QGVAPlayer                     0x11dd4 readBoxTypeAndLength + 304
5  QGVAPlayer                     0x11aa0 -[QGMP4Parser parse] + 1092
6  QGVAPlayer                     0x12c44 -[QGMP4ParserProxy parse] + 32
7  QGVAPlayer                     0x23bcc -[UIView(VAP) ad_instantaneousmud:fps:blendMode:repeatCount:delegate:] + 836
8  iShow                          0x81108 __24-[LSMp4PlayerView parse]_block_invoke + 28 (LSMp4PlayerView.m:28)
```

**Comment by hexleo** [comment]
@wubiner 有空帮忙看看

**Comment by wubiner** [comment]
> 1. 问题描述
>    目前还无法重现，线上抓取的Crash日志
> 2. 运行环境
>    iPhone8
>    15.4.1
>    未越狱
>    竖屏
>    可用RAM：54.14MB
>    可用磁盘：207.5GB
> 3. 日志
> 
> ```
> Crashed: com.apple.main-thread
> 0  libobjc.A.dylib                0xf74c AutoreleasePoolPage::AutoreleasePoolPage(AutoreleasePoolPage*) + 80
> 1  libobjc.A.dylib                0x13cac AutoreleasePoolPage::autoreleaseFullPage(objc_object*, AutoreleasePoolPage*) + 60
> 2  libobjc.A.dylib                0x2a90 objc_object::rootAutorelease2() + 104
> 3  QGVAPlayer                     0x12098 dataConvertToUInt64 + 48
> 4  QGVAPlayer                     0x11dd4 readBoxTypeAndLength + 304
> 5  QGVAPlayer                     0x11aa0 -[QGMP4Parser parse] + 1092
> 6  QGVAPlayer                     0x12c44 -[QGMP4ParserProxy parse] + 32
> 7  QGVAPlayer                     0x23bcc -[UIView(VAP) ad_instantaneousmud:fps:blendMode:repeatCount:delegate:] + 836
> 8  iShow                          0x81108 __24-[LSMp4PlayerView parse]_block_invoke + 28 (LSMp4PlayerView.m:28)
> ```

请告知一下使用的vap版本，如不是最新版可更新

**Comment by fuchenxi** [comment]
使用的就是最新版，目前崩溃48个用户，71次。都是同一个方法

**Comment by wubiner** [comment]
最新版本是1.0.17 看你截图的堆栈不是最新版本。
