### ISSUE TITLE
iOS kColorConversion601FullRange 符号重复问题

### ISSUE THREAD

**Issue by daryl5** [Tencent/vap#257]
iOS 版本 QGHWDMP4OpenGLView.m 文件里，kColorConversion601FullRange 这个常量命名和一个美颜 SDK 里重复了。

影响范围应该不广，不过看了下算是OpenGL里通用的一个矩阵，所以命名重复可能也不止这一例。看看能不能修改一下，谢谢。（没有提 pr，希望能在这里说明白）

**Comment by wubiner** [comment]
ios1.0.18已修复
