### ISSUE TITLE
ios demo中的的vap.mp4星球的动画资源放入android里播放不出来？

### ISSUE THREAD

**Issue by liuleshuai** [Tencent/vap#26]
想在android中看跑车星球那个动效，发现播放不了，android demo中的动画都是没问题的，android和ios的资源应该是通用的，麻烦看下原因（相关资源 iOS/QGVAPlayerDemo/Resource/vap.mp4或vap1.mp4）

**Comment by liuleshuai** [comment]
![image](https://user-images.githubusercontent.com/31751668/100196731-42c5db80-2f34-11eb-9f6d-54ec91aebc9a.png)

**Comment by hexleo** [comment]
ios和Android demo没用同一个素材，你播放的是融合动画，需要你自己判断[imgUser]这个tag，然后返回bitmap才能播放。你给的错误里显示，bitmap为null，所以无法播放

**Comment by liuleshuai** [comment]
> ios和Android demo没用同一个素材，你播放的是融合动画，需要你自己判断[imgUser]这个tag，然后返回bitmap才能播放。你给的错误里显示，bitmap为null，所以无法播放

也就是说，使用融合动画，必须在fetchImage返回bitmap才行，fetchText也不能返回null，是这样么

**Comment by hexleo** [comment]
> 也就是说，使用融合动画，必须在fetchImage返回bitmap才行，fetchText也不能返回null，是这样么

是的

**Comment by liuleshuai** [comment]
这个感觉有点不合理呀，比如跑车这个动效，虽然素材里配置了[imgUser]这个tag，但效果上其实并没有显示头像，这种情况按理说客户端返回null也是可以接受的

**Comment by hexleo** [comment]
这里可以优化下，如果返回null还是能正常播放，只不过没有图片显示在mask那。这里强制要求bitmap的目的是希望保证至少有东西可以展示，比如你希望展示头像，但头像没下载回来，你至少要展示一个占位图

**Comment by liuleshuai** [comment]
> 这里可以优化下，如果返回null还是能正常播放，只不过没有图片显示在mask那。这里强制要求bitmap的目的是希望保证至少有东西可以展示，比如你希望展示头像，但头像没下载回来，你至少要展示一个占位图

如果我用glide去download一个头像资源，在弱网情况下导致头像没有及时下载下来，function1.invoke(BitmapFactory.decodeFile(resource.getAbsolutePath(), options))迟迟没有回调，会有什么问题呢

**Comment by hexleo** [comment]
获取资源的接口 fun fetchImage(resource: Resource, result:(Bitmap?) -> Unit)

回调result() 一定要被调用，不然会永久等待，超时需要业务自己控制回调result

**Comment by liuleshuai** [comment]
能不能提供个超时回调呢。。。大佬

**Comment by liuleshuai** [comment]
这可能是个大坑，毕竟使用vap动效基本都是礼物功能开发，头像资源肯定是拉接口去拿的，可能有人没有及时识别到超时这块的问题

**Comment by hexleo** [comment]
这个问题以前我们讨论过，不同业务有不同的超时逻辑，我们不好统一这个逻辑，所以这个就交由业务自己来决定。
1 不过我们有个改进的想法，新加一个设置url的接口，组件帮助下载

**Comment by liuleshuai** [comment]
你们自己业务使用的处理超时方式是怎样呢？是指定时间内没下载下来就用占位头像嘛？还是由后台返回头像显示的时间，根据这个字段来就判断处理呢？

**Comment by hexleo** [comment]
图片下载组件有自己的超时机制，比如重试次数，最长等待时间等策略。这些都失败之后，我们会用占位图显示

**Comment by liuleshuai** [comment]
好的，了解了，感谢~
