### ISSUE TITLE
华为荣耀X30，动画文件无法正常播放

### ISSUE THREAD

**Issue by D-clock** [Tencent/vap#262]
1. 问题描述：机型必现
2. 运行环境：华为荣耀X30，Android 11
3. 相关日志
```
[AnimPlayer.Decoder][, , 0][onFailed errorType=10002, errorMsg=0x2 MediaCodec exception e=java.lang.IllegalArgumentException

java.lang.RuntimeException:XXX(10002,0x2 MediaCodec exception e=java.lang.IllegalArgumentException)
```
5. 播放错误的文件

https://user-images.githubusercontent.com/6497308/191036178-a4bba889-6590-4417-b042-717296f6c587.mp4

**Comment by hexleo** [comment]
<img width="155" alt="image" src="https://user-images.githubusercontent.com/3285051/191881025-45ba6f96-2070-4f7a-97a8-61bbe9d86337.png">
你这个视频太宽了，可能超出了手机解码限制，而且你这个视频不是vaptool生成的，如果是vaptool生成的话不应该这么长
