### ISSUE TITLE
alpha区域压缩方式请教

### ISSUE THREAD

**Issue by 2449983723** [Tencent/vap#269]
# issue 模版

1. 问题描述（重现路径）
2. 运行环境（Android）
3. 相关日志
4. 播放错误的文件（可选）

有个问题请教下，目前我这边想做下优化，就是把原始图片的透明度信息再压缩下，进一步减小视频分辨率。
基本思路是：将原始图片等分为3份，然后创建一个原始图片1/3大小的区域，用于存储alpha值，比如r的色值用于存第一个1/3区域的alpha值，g用于存储第二个1/3，b用于存储第三个1/3，这样可以充分利用额外的alpha区域。
问题：
1、按照这种方式处理后，发现将处理好的图片合成mp4，视频元素的边界区域会出现黑边（如果直接用图片展示对应帧，不会出现黑边），怀疑应该是图片合成视频后，会对图片的原始色值进行压缩，导致色值产生一定偏差（特别是元素边界），导致本来alpha应该是0的地方，出现了alpha值不为0，所以出现了黑边。

想请教下，vap的素材制作，这方面有没有什么经验可以分享下，非常感谢。（vap选择的压缩方式是缩放的压缩方式，没有选择将rgb值都填充满，是否也是这个原因？）

**Comment by 2449983723** [comment]
补充说明一下，如果采用无损压缩，即ffmpeg的-crf设置为0，则不会出现上面的问题，可以确定是视频压缩的时候会对色值产生一定偏差。

其实想做这个优化的核心目的就是减少视频码率（和视频分辨率、质量有关），一个是减少视频大小，另外一个是提高视频播放机型的兼容性，如果采用这种压缩方式，必须要无损压缩，反而会影响增大视频码率，还不如不做这个优化。

想请问下vap这边目前采用的缩放压缩方式，是否可以规避此类问题，非常感谢。

**Comment by hexleo** [comment]
1 利用3通道压缩：你这种思路之前我们也尝试过，但视频压缩是有损的，所以无法利用3个通道存不同的值实现压缩。
2 vap现在的存储alpha的方式，是将rgb设置为相同的值，这样就能得到“灰度图”，转成视频后基本只有y值，uv都是0，yuv420 用y来还原alpha精度更高。虽然分辨率没变小，但文件大小会比单独存储在某一个通道要小一点。

**Comment by 2449983723** [comment]
明白了，感谢。
