### ISSUE TITLE
*** -[NSConcreteFileHandle seekToFileOffset:]: Illegal seek 

### ISSUE THREAD

**Issue by AbnerPei** [Tencent/vap#270]
## 如图
![image](https://user-images.githubusercontent.com/11939807/196906090-de1fc85e-a3dd-4e5b-ab88-aac04ebea037.png)
![image](https://user-images.githubusercontent.com/11939807/196906483-0676bd36-4278-45b4-b9f4-20333375fdc9.png)

只在iOS12.4以下崩溃！ 线下也未遇到过，最近2周，听云崩溃率排第一！
![image](https://user-images.githubusercontent.com/11939807/196906986-69da246e-1ca1-4289-9fb4-44f19d307bcc.png)

**Comment by hexleo** [comment]
使用的版本？具体是哪个文件，还是所有文件都遇到？

**Comment by AbnerPei** [comment]
> 使用的版本？具体是哪个文件，还是所有文件都遇到？

不好意思，最近在忙着业务开发，今天有时间了才看这个，版本目前用的是1.0.18，具体是哪个文件，还是所有文件，我不清楚，看不到。但是今天看了下设备统计，集中在8p以下机型：
![image](https://user-images.githubusercontent.com/11939807/198920060-7890eb97-3c1d-409d-831d-4600853a965f.png)

**Comment by hexleo** [comment]
> > 使用的版本？具体是哪个文件，还是所有文件都遇到？
> 
> 今天早上，我再看听云后台，发现了一个崩溃路径（我们登录页顶部用的vap动画），然后我模拟场景，虽然没有崩溃，但是控制台打印了很多如下信息： 2022-11-01 10:58:16.794110+0800 我们APP[57371:2019512] <2> QGMP4FrameHWDecoder.m(386):-[QGMP4FrameHWDecoder initPPSnSPS] [kQGVAPModuleCommon] - initPPSnSPS 2022-11-01 10:58:16.831444+0800 我们APP[57371:2019512] <2> UIView+VAP.m(515):-[UIView(VAP) decoderDidFinishDecode:] [kQGVAPModuleCommon] - decoderDidFinishDecode. 2022-11-01 10:58:16.831914+0800 我们APP[57371:2019512] <2> UIView+VAP.m(155):-[UIView(VAP) hwd_didFinishDisplay] [kQGVAPModuleCommon] - hwd didFinishDisplay 2022-11-01 10:58:16.832390+0800 我们APP[57371:2019512] <2> UIView+VAP.m(165):-[UIView(VAP) hwd_didFinishDisplay] [kQGVAPModuleCommon] - continue to display. currentCount:-1 2022-11-01 10:58:16.832805+0800 我们APP[57371:2019512] <2> UIView+VAP.m(302):-[UIView(VAP) p_playHWDMP4:fps:blendMode:repeatCount:delegate:] [kQGVAPModuleCommon] - try to display mp4:/private/var/containers/Bundle/Application/E46840E1-BB92-432E-904C-6C3785E306F3/我们APP.app/gb_login_bg_head.mp4 blendMode:0 fps:0 repeatCount:-1 2022-11-01 10:58:16.835648+0800 我们APP[57371:2019512] <5> QGVAPConfigManager.m(173):-[QGVAPConfigManager parseConfigDictinary:] [kQGVAPModuleCommon] - has no sourcesArr:{
> 
> <img alt="image" width="1021" src="https://user-images.githubusercontent.com/11939807/199150213-7bb8635b-b809-4dcb-919f-ba6cdc0997fd.png">
> 
> mp4资源：gb_login_cat_head.mp4 链接: https://pan.baidu.com/s/1DfL3u_OylFgHm11F4YVi8w 提取码: qgan

你这个日志看着挺正常。

你们下载mp4的后有没有工具生成的md5进行校验？感觉像mp4文件被修改，导致解析crash了

**Comment by AbnerPei** [comment]
> > > 使用的版本？具体是哪个文件，还是所有文件都遇到？
> > 
> > 
> > 今天早上，我再看听云后台，发现了一个崩溃路径（我们登录页顶部用的vap动画），然后我模拟场景，虽然没有崩溃，但是控制台打印了很多如下信息： 2022-11-01 10:58:16.794110+0800 我们APP[57371:2019512] <2> QGMP4FrameHWDecoder.m(386):-[QGMP4FrameHWDecoder initPPSnSPS] [kQGVAPModuleCommon] - initPPSnSPS 2022-11-01 10:58:16.831444+0800 我们APP[57371:2019512] <2> UIView+VAP.m(515):-[UIView(VAP) decoderDidFinishDecode:] [kQGVAPModuleCommon] - decoderDidFinishDecode. 2022-11-01 10:58:16.831914+0800 我们APP[57371:2019512] <2> UIView+VAP.m(155):-[UIView(VAP) hwd_didFinishDisplay] [kQGVAPModuleCommon] - hwd didFinishDisplay 2022-11-01 10:58:16.832390+0800 我们APP[57371:2019512] <2> UIView+VAP.m(165):-[UIView(VAP) hwd_didFinishDisplay] [kQGVAPModuleCommon] - continue to display. currentCount:-1 2022-11-01 10:58:16.832805+0800 我们APP[57371:2019512] <2> UIView+VAP.m(302):-[UIView(VAP) p_playHWDMP4:fps:blendMode:repeatCount:delegate:] [kQGVAPModuleCommon] - try to display mp4:/private/var/containers/Bundle/Application/E46840E1-BB92-432E-904C-6C3785E306F3/我们APP.app/gb_login_bg_head.mp4 blendMode:0 fps:0 repeatCount:-1 2022-11-01 10:58:16.835648+0800 我们APP[57371:2019512] <5> QGVAPConfigManager.m(173):-[QGVAPConfigManager parseConfigDictinary:] [kQGVAPModuleCommon] - has no sourcesArr:{
> > <img alt="image" width="1021" src="https://user-images.githubusercontent.com/11939807/199150213-7bb8635b-b809-4dcb-919f-ba6cdc0997fd.png">
> > mp4资源：gb_login_cat_head.mp4 链接: https://pan.baidu.com/s/1DfL3u_OylFgHm11F4YVi8w 提取码: qgan
> 
> 你这个日志看着挺正常。
> 
> 你们下载mp4的后有没有工具生成的md5进行校验？感觉像mp4文件被修改，导致解析crash了

没有，UI给我们的，直接导入项目

**Comment by hexleo** [comment]
@wubiner 有空看看这个问题，很奇怪只有特定ios版本才会出现偶现的crash

**Comment by wubiner** [comment]
应该是和文件有关系，估计是文件解析帧数据异常，seek文件的偏移位置有问题。建议找同样iOS的系统复现看看。
