### ISSUE TITLE
Metal Drawable对象释放问题

### ISSUE THREAD

**Issue by illusionspaces** [Tencent/vap#273]
根据 https://developer.apple.com/documentation/quartzcore/cametallayer 
文档描述，apple建议render方法使用自动释放池包裹：
autoreleasepool {
        render(view: view)
}
vap 没有看到对 Drawable 对象的释放逻辑，这可能会导致 layer.nextDrawable 调用产生卡顿

**Comment by wubiner** [comment]
渲染每一帧时，最外层在autoreleasepool包裹的。如果你确实遇到线上卡顿，可以将修复的代码提交merge request
