### ISSUE TITLE
播放预览工具似乎不work了，还有在维护吗

### ISSUE THREAD

**Issue by lzb6666** [Tencent/vap#275]
播放预览工具无法正常工作 [https://github.com/Tencent/vap/releases/download/VapPreview1.2.0/vap-player_1.2.0.exe]
播放时如下是预期之内的吗
![image](https://user-images.githubusercontent.com/31194937/202399755-e3c493e6-b296-4591-95f2-9f8c5aaae7c5.png)

**Comment by hexleo** [comment]
应该是可以的，你这个视频不是vaptool导出的，所以无法用vap预览工具来看
