### ISSUE TITLE
融合动画图片资源放缩方式的问题

### ISSUE THREAD

**Issue by lzb6666** [Tencent/vap#276]
issue 模版

1. 问题描述
 使用Vap导出工具，导出设置放缩方式为centerCrop的图片类型遮罩，实际播放时发现图片仍有不等比拉伸。查看代码发现，在计算Src图片纹理坐标的时候，拉伸方式的方式的实现是通过帧中显示区域 (frame.w frame.h) 与 src中的宽高（即vapc box里src的w、h，这个宽高查看vap tool是从mask序列帧中，取最大的遮罩矩形的宽高）做计算，如果src的宽高与实际图片纹理的宽高不同，就会导致centerCrop类型，图片仍然会被拉伸。
```
// src 纹理坐标
srcArray.setArray(genSrcCoordsArray(srcArray.array, frame.frame.w, frame.frame.h, src.w, src.h, src.fitType))
srcArray.setVertexAttribPointer(shader.aTextureSrcCoordinatesLocation)
```
效果如图（注意原本图片中的是圆而不是椭圆）：
![image](https://user-images.githubusercontent.com/31194937/202650011-c1f4be35-f0cf-472d-8e88-0c90246c7e4d.png)

如果要保证图片不被拉伸，这里计算坐标时应该使用图片纹理的坐标去计算
```
// src 纹理坐标
srcArray.setArray(genSrcCoordsArray(srcArray.array, frame.frame.w, frame.frame.h, bitmap.w, bitmap.h, src.fitType))
srcArray.setVertexAttribPointer(shader.aTextureSrcCoordinatesLocation)
```
效果如图：
![image](https://user-images.githubusercontent.com/31194937/202650238-37dca39b-599b-47f6-a640-e300caa7f7d9.png)

不确定这是一个bug还是设计如此，但我倾向于是个bug，因为iOS使用同样的文件不会被拉伸。望解答

**Comment by hexleo** [comment]
确实是bug，我修复下

**Comment by hexleo** [comment]
感谢反馈，具体原因CENTER_FULL 并不是严格的centerCrop，主要是为防抖动，复杂遮罩情况下需要固定src大小进行绘制防止抖动，目前centerCrop已经前置处理，已经发布2.0.28你可以试试
