### ISSUE TITLE
ios库parse解析异常

### ISSUE THREAD

**Issue by Arokenda** [Tencent/vap#277]
# issue 模版

问题：
这样的代码对应打印
<img width="803" alt="image" src="https://user-images.githubusercontent.com/7910601/203747004-f590a650-3ec7-4bc9-b5ab-ea278ea8d874.png">

![image](https://user-images.githubusercontent.com/7910601/203745573-6d508bf8-fe4e-4f05-a9c9-9a7d9ea08bf7.png)

Length = 0 异常， 必现死循环，该现象只在构建包里出现，xcode连手机debug包不会出现

同样构建包，加了两行日志后，对应打印
<img width="796" alt="image" src="https://user-images.githubusercontent.com/7910601/203746857-b0efe721-440a-43cc-90ec-e88fabe7effc.png">
![image](https://user-images.githubusercontent.com/7910601/203745916-f14c8105-980d-4708-ac5e-dc07eb9e91c5.png)

解析length正常了

QGVAPlayer版本 1.0.16
升级到1.0.17现象一样

赋上资源，感谢大佬排查一下

**Comment by Arokenda** [comment]
https://user-images.githubusercontent.com/7910601/203746444-9d57b9d9-a546-4b23-bb9c-7b55ae7d5227.mp4

**Comment by wubiner** [comment]
你确定你用1.0.17还有问题？1.0.17针对length=0的情况，直接有break。如果确认的话，麻烦贴一下1.0.17版本的代码调试。

**Comment by Arokenda** [comment]
> 你确定你用1.0.17还有问题？1.0.17针对length=0的情况，直接有break。如果确认的话，麻烦贴一下1.0.17版本的代码调试。

是的大佬，主要是当length=1的时候会去读后面8位的largeSize，此时读出来的是0，所以offset+length没变化

另外发现一个资源结尾处是用0补齐的，所以rootBox的size直接=fileSize也是会出现解析异常，无限循环

**Comment by wubiner** [comment]
你的意思是在1.0.17这个函数release包返回的value依旧是0？但是debug包是正常的？
<img width="586" alt="image" src="https://user-images.githubusercontent.com/24598274/203751989-07e7d141-773e-42a5-9539-5679b531d689.png">

**Comment by wubiner** [comment]
> > 你确定你用1.0.17还有问题？1.0.17针对length=0的情况，直接有break。如果确认的话，麻烦贴一下1.0.17版本的代码调试。
> 
> 是的大佬，主要是当length=1的时候会去读后面8位的largeSize，此时读出来的是0，所以offset+length没变化
> 
> 另外发现一个资源结尾处是用0补齐的，所以rootBox的size直接=fileSize也是会出现解析异常，无限循环

      *length = [self readValue:bytes length:kQGBoxLargeSizeLengthInBytes];
      // 补充以下内容
      if *length == 0 {
        VAP_Error(kQGVAPModuleCommon, @"read box length is 0");
        return NO;
      }
      麻烦你补充以下内容再试试呢

**Comment by Arokenda** [comment]
> 

好的大佬，我再试试

**Comment by Arokenda** [comment]
> > > 你确定你用1.0.17还有问题？1.0.17针对length=0的情况，直接有break。如果确认的话，麻烦贴一下1.0.17版本的代码调试。
> > 
> > 
> > 是的大佬，主要是当length=1的时候会去读后面8位的largeSize，此时读出来的是0，所以offset+length没变化
> > 另外发现一个资源结尾处是用0补齐的，所以rootBox的size直接=fileSize也是会出现解析异常，无限循环
> 
> ```
>   *length = [self readValue:bytes length:kQGBoxLargeSizeLengthInBytes];
>   // 补充以下内容
>   if *length == 0 {
>     VAP_Error(kQGVAPModuleCommon, @"read box length is 0");
>     return NO;
>   }
>   麻烦你补充以下内容再试试呢
> ```

大佬，我拉出来的1.0.17版本的代码，并没有这一行返回哦，
<img width="806" alt="image" src="https://user-images.githubusercontent.com/7910601/203756798-84c4e016-83c0-4596-8577-9483022aa675.png">

**Comment by wubiner** [comment]
我意思是，如果你确认截图的那个函数返回的length依旧还会为0的话，那麻烦你自己添加一下

**Comment by Arokenda** [comment]
fhxm

> 我意思是，如果你确认截图的那个函数返回的length依旧还会为0的话，那麻烦你自己添加一下

嗯嗯，好的，目前是这样先解决的，只是针对这个函数为何返回0，想不明白，所以想请教大佬

**Comment by wubiner** [comment]
> fhxm
> 
> > 我意思是，如果你确认截图的那个函数返回的length依旧还会为0的话，那麻烦你自己添加一下
> 
> 嗯嗯，好的，目前是这样先解决的，只是针对这个函数为何返回0，想不明白，所以想请教大佬

这里因为release有编译优化，传入的参数都是常数。

**Comment by wubiner** [comment]
修改已提交
