### ISSUE TITLE
视频在moto 4x上底部出现绿边

### ISSUE THREAD

**Issue by gejiashu** [Tencent/vap#278]
按照其他的问题把视频分辨率降到1504之后就没有绿边的问题了，想请教下出现绿边的原因是什么 。
![POPO20221129-094117](https://user-images.githubusercontent.com/7670817/204418089-0339a6a8-267d-40ff-8e57-de9875d73fa8.png)

**Comment by hexleo** [comment]
不同机器有解码有限制，太大了容易出现绿边，有些机器渲染缓存大小有限制，太大了也会出现绿边，只能去兼容适配

**Comment by JungleJie** [comment]
请问怎么去做前置判断 这个解码器的解码尺寸限制？
