### ISSUE TITLE
最新版本VAP播放MP4偶现崩溃

### ISSUE THREAD

**Issue by xiaowangqinghui** [Tencent/vap#281]
最近用最新版本的VAP 播放mp4 经常会遇到这个崩溃（不是必现，但是概率很大）  能看下怎么回事吗  手机系统有iOS13的  也有iOS16的，
![A7A5249B6AA9487E40914CF2FC459E52](https://user-images.githubusercontent.com/15713276/206390772-12745f66-3cc8-47f9-b8ad-3ab2809dc2f0.png)
![image](https://user-images.githubusercontent.com/15713276/206390798-e3292136-9ac3-459b-98a0-1341842b753d.png)

**Comment by hexleo** [comment]
麻烦补充下版本信息，复现方式，和详细的播放log

**Comment by wubiner** [comment]
麻烦贴一下完整的crash日志

**Comment by xiaowangqinghui** [comment]
上面不是都有截图了吗  还要什么样的日志  没有啊
