### ISSUE TITLE
使用UIView播放mp4文件可以设置contentMode不起作用

### ISSUE THREAD

**Issue by Cuizhangqiang** [Tencent/vap#284]
使用UIView播放mp4文件可以设置contentMode不起作用

**Comment by wubiner** [comment]
请参考demo使用。

**Comment by Cuizhangqiang** [comment]
> 请参考demo使用。

必须使用这个才可以吗，QGVAPWrapView，使用这个会报没有vpc box

**Comment by Cuizhangqiang** [comment]
对视频格式具体要求是什么

**Comment by wubiner** [comment]
> > 请参考demo使用。
> 
> 必须使用这个才可以吗，QGVAPWrapView，使用这个会报没有vpc box

只有QGVAPWrapView支持缩放适配，QGVAPWrapView的使用要求素材必须是vap tool生成的。

**Comment by Cuizhangqiang** [comment]
vap tool 可以 批量把我们之前的所有 mp4 文件动画效果 ，快速的转换成 QGVAPWrapView 要求的格式吗？能批量转换吗？

**Comment by wubiner** [comment]
> vap tool 可以 批量把我们之前的所有 mp4 文件动画效果 ，快速的转换成 QGVAPWrapView 要求的格式吗？能批量转换吗？

不支持。vap tool只可以用图片素材进行视频合成。
