### ISSUE TITLE
个别荣耀x30设备播放失败

### ISSUE THREAD

**Issue by 1wayticket** [Tencent/vap#285]
# issue 模版

1. 使用demo项目播放动画，demo里的动画可以播放，但是我们自制的vap动画播放失败
2. 荣耀x30 Android 10    sdk最新版本 用的是github上demo
3. 相关日志如下

12-20 14:50:10 23838 23924 I AnimPlayer.FileContainer: FileContainer init
--
112-20 14:50:10 23838 23924 I AnimPlayer.AnimConfigManager: parseConfig cost=1ms enableVersion1=false result=true
212-20 14:50:10 23838 23924 I AnimPlayer.AnimPluginManager: onConfigCreate
312-20 14:50:10 23838 23924 I AnimPlayer.AnimPlayer: parse AnimConfig(version=2, totalFrames=120, width=720, height=1440, videoWidth=1456, videoHeight=1440, orien=0, fps=24, isMix=false, alphaPointRect=PointRect(x=724, y=0, w=720, h=1440), rgbPointRect=PointRect(x=0, y=0, w=720, h=1440), isDefaultConfig=false)
412-20 14:50:10 23838 23924 I AnimPlayer.ScaleTypeUtil: scaleType=FIT_CENTER
512-20 14:50:10 23838 23924 I AnimPlayer.AnimView: onSurfaceTextureAvailable width=1080 height=2160
612-20 14:50:10 23838 23924 I AnimPlayer.MediaUtil: Extractor selected track 0 (video/avc): {max-bitrate=2007876, track-id=1, level=2048, mime=video/avc, frame-count=120, profile=2, bitrate=2007876, language=und, display-width=1456, csd-1=java.nio.HeapByteBuffer[pos=0 lim=8 cap=8], durationUs=5000000, display-height=1440, width=1456, max-input-size=16220, frame-rate=24, height=1440, csd-0=java.nio.HeapByteBuffer[pos=0 lim=28 cap=28]}
712-20 14:50:10 23838 23924 E AnimPlayer.AudioPlayer: cannot find audio track
812-20 14:50:10 23838 23924 I AnimPlayer.HardDecoder: Video size is 1456 x 1440
912-20 14:50:10 23838 23924 I AnimPlayer.Decoder: prepareRender
1012-20 14:50:10 23838 23924 I AnimPlayer.AnimPluginManager: onRenderCreate
1112-20 14:50:10 23838 23924 I AnimPlayer.MaskAnimPlugin: mask render init
1212-20 14:50:10 23838 23924 I AnimPlayer.HardDecoder: Video MIME is video/avc
1312-20 14:50:10 23838 23924 E AnimPlayer.HardDecoder: start failed
14android.media.MediaCodec$CodecException: start failed
15at android.media.MediaCodec.native_start(Native Method)
16at android.media.MediaCodec.start(MediaCodec.java:2284)
17at com.tencent.qgame.animplayer.HardDecoder.startPlay(HardDecoder.kt:168)
18at com.tencent.qgame.animplayer.HardDecoder.access$startPlay(HardDecoder.kt:29)
19at com.tencent.qgame.animplayer.HardDecoder$start$1.run(HardDecoder.kt:58)
20at android.os.Handler.handleCallback(Handler.java:955)
21at android.os.Handler.dispatchMessage(Handler.java:102)
22at android.os.Looper.loopOnce(Looper.java:206)
23at android.os.Looper.loop(Looper.java:296)
24at android.os.HandlerThread.run(HandlerThread.java:67)
25
2612-20 14:50:10 23838 23924 E AnimPlayer.Decoder: onFailed errorType=10002, errorMsg=0x2 MediaCodec exception e=android.media.MediaCodec$CodecException: start failed
2712-20 14:50:10 23838 23924 I AnimSimpleDemoActivity: onFailed errorType=10002 errorMsg=0x2 MediaCodec exception e=android.media.MediaCodec$CodecException: start failed

5. [播放失败的问题动画文件](url：https://static.mszmapp.com/files/20210923/521d76c45e633beba93762009fffbf7e.mp4)

问题：
1 使用demo里的示例在荣耀x30异常设备里可以正常播放，但是一旦demo.mp4替换成我们的动画文件，就会播放失败。
2 并不是所有的荣耀x30都会播放失败，目前已知个别荣耀x30设备出现该问题。

**Comment by hexleo** [comment]
你可以补充下素材，我这没有荣耀x30这手机，没有重现这个问题，怀疑是这台手机对解码高分辨率的视频又兼容问题，你可以试试把素材分辨率降低到1024再试试

**Comment by 1wayticket** [comment]
> 你可以补充下素材，我这没有荣耀x30这手机，没有重现这个问题，怀疑是这台手机对解码高分辨率的视频有兼容问题，你可以试试把素材分辨率降低到1024再试试

vap有api可以修改解析出来的帧大小吗？我们不想通过修改公共文件分辨率的方式去规避问题，我们在想通过判定设备型号去调整分辨率规避问题。

**Comment by hexleo** [comment]
"2 vap有api可以修改解析出来的帧大小吗？"，开始播放前有个onVideoConfigReady的回调

你们还有注意区分是不是模拟器在播放，之前有遇到过模拟器播放失败的问题，我们不保证模拟器的播放情况

**Comment by 1wayticket** [comment]
> "2 vap有api可以修改解析出来的帧大小吗？"，开始播放前有个onVideoConfigReady的回调
> 
> 你们还有注意区分是不是模拟器在播放，之前有遇到过模拟器播放失败的问题，我们不保证模拟器的播放情况

我们把动画从720*1440改成360*720，玩家设备可以正常播放。那看来就是该设备不支持太高分辨率的动画，我们试下针对该类型设备降低解析的分辨率。

**Comment by hexleo** [comment]
> > "2 vap有api可以修改解析出来的帧大小吗？"，开始播放前有个onVideoConfigReady的回调
> > 你们还有注意区分是不是模拟器在播放，之前有遇到过模拟器播放失败的问题，我们不保证模拟器的播放情况
> 
> 我们把动画从720x1440改成360x720，玩家设备可以正常播放。那看来就是该设备不支持太高分辨率的动画，我们试下针对该类型设备降低解析的分辨率。 玩家设备就是真实设备，不是模拟器。vap有考虑对这种设备做解析优化吗？避免宽高问题导致视频解析失败。

使用硬件解码没有太好的方法，无法修改硬件内容。软件解码到是可以，但有开源协议问题，不能引入到vap，你可以自己支持。

**Comment by 1wayticket** [comment]
> "2 vap有api可以修改解析出来的帧大小吗？"，开始播放前有个onVideoConfigReady的回调
> 
> 你们还有注意区分是不是模拟器在播放，之前有遇到过模拟器播放失败的问题，我们不保证模拟器的播放情况

onVideoConfigReady 里面修改width和height依旧提示解析失败
但是如果我们把动画源文件大小改小就可以播放，所以我认为是修改width和height没生效，麻烦给确认下原因。
