### ISSUE TITLE
web端不能同时播放两个vap实例吗？

### ISSUE THREAD

**Issue by ape-casear** [Tencent/vap#29]
我如果在播放第一个vap实例的过程中， new 第二个Vap实例， 就会导致第一个vap的canvas消失，而且第二个vap播放的时候也有问题。 隐隐约约能看到第一个vap的内容在第二个vap里面闪烁

**Comment by ape-casear** [comment]
两个vap用一个canvas，然后options使用给不同的type就好了。

**Comment by hujinliang** [comment]
前端使用type实现了实例缓存，对于一处动画，播放完之后播放第二次可以不需要初始化工作，也会复用canvas和glContext等等；所以想创建可以同时播放的动画需要传入不同的type值，如1、2、3、4等等，已更新文档，有问题欢迎咨询~

**Comment by ape-casear** [comment]
web vap要是能支持OffscreenCanvas就好了， 我这里是有多个vap实例同时播放的情况

**Comment by hujinliang** [comment]
我们最终画面是呈现在canvas元素上的，多个vap实例同时播放可以使用不同的type创建不同的canvas，应该不会有问题吧，这里OffscreenCanvas的作用没看出来，可以参考[DEMO](https://egame.qq.com/vap)

**Comment by ape-casear** [comment]
想使用OffscreenCanvas是想用web worker分担压力，不卡顿

**Comment by hujinliang** [comment]
我晚点研究下
