### ISSUE TITLE
安卓播放融合图片偶现图片位置变成黑色

### ISSUE THREAD

**Issue by ysxlmk** [Tencent/vap#290]
1. 安卓播放融合图片偶现图片位置变成黑色，重复播放同一个融合动画会偶现
2. Android手机，版本型号无关
调用的api  VapFetchResourceCallBack   addResource()

**Comment by hexleo** [comment]
这个你看看是否能在demo里复现，估计是业务问题，检查下bitmap生命周期是否正确

**Comment by huanghongfu** [comment]
VapFetchResourceCallBack 这个东西在哪里
