### ISSUE TITLE
崩溃问题

### ISSUE THREAD

**Issue by xiaowangqinghui** [Tencent/vap#293]
我这里有个这样的崩溃  能有什么办法定位是在哪里的吗  用到vap播放的mp4文件 就大概率会崩  没用到的话 就一定不会崩。。。手机上的崩溃日志见附件。bugly也解析不出来崩在哪里 #
[Whisper-2023-02-21-140510.ips.zip](https://github.com/Tencent/vap/files/10793052/Whisper-2023-02-21-140510.ips.zip)

**Comment by hexleo** [comment]
使用的是什么版本，能否在demo上复现？

**Comment by wubiner** [comment]
如qq回复，从提供的信息无法推断原因，只能自行debug排查项目主线程调用代码

**Comment by xiaowangqinghui** [comment]
执行静音代码后 崩溃貌似没出现过了（[mp4View setMute:YES];）
https://user-images.githubusercontent.com/15713276/220594757-23e3d402-7cff-4fa3-9b68-acaacc139810.mp4

**Comment by xiaowangqinghui** [comment]
执行静音代码后 崩溃貌似没出现过了（[mp4View setMute:YES];）素材文件如下

https://user-images.githubusercontent.com/15713276/220595115-a9d93a84-42f2-4aac-8e01-4dca29507ddf.mp4
