### ISSUE TITLE
视频用微帧转码后播放器解码报错，播放器能兼容吗？

### ISSUE THREAD

**Issue by doubleYang1020** [Tencent/vap#298]
1 问题描述
由于导出的视频太大了，我们用微帧进行转码操作，播放器用的是vap兼容模式，视频header box 中不包含 vap info
2 运行环境
iPhone 12  iOS15.0
3 相关日志
QGMP4FrameHWDecoder.m(312):-[QGMP4FrameHWDecoder handleDecodePixelBuffer:sampleBuffer:frameIndex:currentPts:startDate:status:needDrop:] [kQGVAPModuleCommon] - decompress fail! frame:0 kVTVideoDecoderBadDataErr error:-12909
4 播放错误的文件
https://videocdn.poizon.com/node-common/a3837121-30ea-4b6c-edaa-c28f7a3cbe8a.mp4

**Comment by hexleo** [comment]
不能再次转码，如果文件太多可以通过修改码率或修改-crf参数实现
