### ISSUE TITLE
播放普通mp4文件，出现卡帧

### ISSUE THREAD

**Issue by chenjianlei** [Tencent/vap#30]
[这是正常画面](https://cherry-sztest.oss-cn-hangzhou.aliyuncs.com/res/video_test_2.mov)
[这是有手机demo](https://cherry-sztest.oss-cn-hangzhou.aliyuncs.com/res/video_test_1.mp4)

**Comment by hexleo** [comment]
可以更新最新的ios代码，应该不会再有此问题，最新版本ios已经支持b帧播放

**Comment by chenjianlei** [comment]
> 可以更新最新的ios代码，应该不会再有此问题，最新版本ios已经支持b帧播放

感谢回复，问题已经解决，谢谢
