### ISSUE TITLE
Android手机播放vap时，会自动把web页面背景音乐暂停

### ISSUE THREAD

**Issue by MrJ6336017** [Tencent/vap#300]
1. 问题描述（重现路径）：web页面上有背景音乐正在播放时，只要vap动效一播放，背景音乐就会自动被暂停，即使vap已设置静音。
2. 运行环境（手机型号，Android/iOS版本等）：Android手机才会，iOS正常。

**Comment by hexleo** [comment]
手机webview建议使用vap，兼容不好

**Comment by MrJ6336017** [comment]
> 手机webview建议使用vap，兼容不好

是说“不建议”？

**Comment by hexleo** [comment]
vap之前没有对手机webview有专门支持
