### ISSUE TITLE
web播放后导致系统内存过高不知道是哪里问题

### ISSUE THREAD

**Issue by mango-Yu** [Tencent/vap#307]
web播放后导致系统内存过高不知道是哪里问题。
使用最新版本的js不能直接html直接引用
`<script src="../node_modules/video-animation-player/dist/vap.js"></script>`
` var vap = new Vap()`
`Vap is not a constructor`
这样使用报错需要咋处理

**Comment by note744** [comment]
new Vap.default()

**Comment by note744** [comment]
> web播放后导致系统内存过高不知道是哪里问题。 使用最新版本的js不能直接html直接引用 `<script src="../node_modules/video-animation-player/dist/vap.js"></script>` ` var vap = new Vap()` `Vap is not a constructor` 这样使用报错需要咋处理


应该这样
new Vap.default()
