### ISSUE TITLE
在动画执行过程中动态改变AnimView的大小，动画会有几帧出现异常。

### ISSUE THREAD

**Issue by gejiashu** [Tencent/vap#310]
# issue 模版

1. 问题描述 使用ScaleType.FIT_XY 把AnimView的大小修改了，比如AnimView大小从1080x1080 修改为 540x540 
2. 运行环境 Android

**Comment by gejiashu** [comment]
Uploading Screen_Recording_20230419_134037_AnimPlayer.mp4…

**Comment by gejiashu** [comment]
https://user-images.githubusercontent.com/7670817/232977802-afa6d04e-5675-4b94-8987-760e4b4c2ee0.mp4

**Comment by gejiashu** [comment]
上面的是出现问题的视频，通过debug观察，改变AnimView的大小之后，Render里面的glViewPort是有正常调用的，但是调用之后貌似没有立即生效，渲染了两帧错误的位置和大小时候才会在以正常的位置和大小来渲染。下面的图是在错误的位置渲染的那两帧

**Comment by gejiashu** [comment]
![Screenshot_20230419-134809_Video Editor](https://user-images.githubusercontent.com/7670817/232978595-4d026944-b635-4357-a8fc-6fc1f21cb392.jpg)

**Comment by gejiashu** [comment]
正常情况下 动画应该是在居中显示在AnimView中间的。在动画执行过程中修改了AnimView的宽高会出现这种情况。

**Comment by hexleo** [comment]
不支持动画过程中改变大小，如有需要改变大小可以重新播放

**Comment by gejiashu** [comment]
好的，那只能换种方式了，因为用的是TextureView 试了一下可以通过修改scaleX scaleY来实现， 实现视觉上动画变成原来的一半大小。
