### ISSUE TITLE
透明度与实际效果不符

### ISSUE THREAD

**Issue by swearToGod** [Tencent/vap#318]
<img width="204" alt="01" src="https://user-images.githubusercontent.com/28703085/235041613-000aa55a-7ffb-42ef-ad39-132a7cfa4c0b.png">

1. 如上图，关注紫色背景的底色，设计师出的紫色颜色深，iOS展现效果颜色浅，透明度有变化，同样的mp4资源，andriod可以正确展示透明度。
2. 官方vap Demo. iOS版本也可以复现。采用的是三种方案里的最后一种(使用WrapView，支持ContentMode). 没有报错日志，除了透明度其他表现正常.

**Comment by demoker** [comment]
https://github.com/Tencent/vap/assets/10993817/7f70c7ee-5fbb-44e0-8f85-bb84ae4a9ec5

@akanchi  哈喽大佬 邮件请教来着，上面是素材，在demo中展示也是同样的问题，一个是范围变小了，一个是色彩变淡了
