### ISSUE TITLE
融合文字表现的过于小了

### ISSUE THREAD

**Issue by wangbo122** [Tencent/vap#319]
# 融合文字表现的过于小了

这是融合信息的位置和预览图
![image](https://user-images.githubusercontent.com/61643139/235130475-85fc57e2-4a6a-406f-921a-fc3491a50691.png)

这是最终展示出来的效果
![image](https://user-images.githubusercontent.com/61643139/235130558-4814bf1e-fd58-465d-a4c6-fda98bf701d9.png)

![image](https://user-images.githubusercontent.com/61643139/235131232-c7e51d3d-2daf-4d42-914e-d5cca5869812.png)
最后查出来，是这里取fontSize的时候，最小值h-8，个人感觉阈值有点过大，导致全部都走后面h-8了
想问一下这里最开始是出于什么目的-8的，我改成-1用于生产可以吗？

**Comment by hexleo** [comment]
可以自己绘制文字bitmap，这样更灵活
