### ISSUE TITLE
tag版本与spec文件不统一，导致找不到1.0.3

### ISSUE THREAD

**Issue by chenjianlei** [Tencent/vap#32]

**Comment by hexleo** [comment]
@mlzhangyu ios版本问题

**Comment by mlzhangyu** [comment]
podspec已更新

**Comment by chenjianlei** [comment]
> podspec已更新

大佬，你只更新podspec文件，难道不需要重新打一个tag么？ 根本pod不下来啊。。。。。。。

**Comment by DKJone** [comment]
> > podspec已更新
> 
> 大佬，你只更新podspec文件，难道不需要重新打一个tag么？ 根本pod不下来啊。。。。。。。

` pod 'QGVAPlayer', :git => 'https://github.com/Tencent/vap.git', :tag => '1.0.4'`
