### ISSUE TITLE
融合文字 ，当文字中包含emoji时，emoji 颜色不能准确识别，只有一种颜色

### ISSUE THREAD

**Issue by XiaoXunLu** [Tencent/vap#323]
融合文字 ，当文字中包含emoji时，emoji 颜色不能准确识别，只有一种颜色

例如： 文字中有个 笑哭的眼睛表情，头像中的眼睛 眼泪的颜色都变成了文字的黄色，整个emoji的颜色都变成了文字的颜色 ，使表情都是一个轮廓图

**Comment by hexleo** [comment]
enableAutoTxtColorFill
有这个接口可以关闭颜色填充，但会导致文字效果带黑边，建议自己绘制文字bitmap效果更好
