### ISSUE TITLE
为什么我提出的问题没有任何回复就被删除了？

### ISSUE THREAD

**Issue by XiaoXunLu** [Tencent/vap#326]
为什么我提出的问题没有任何回复就给我删除了？   请回复 请回复！

**Comment by wubiner** [comment]
这个？
<img width="1109" alt="image" src="https://github.com/Tencent/vap/assets/24598274/caa1f997-aaa1-4e02-b2eb-212474297d44">

**Comment by XiaoXunLu** [comment]
是的
