### ISSUE TITLE
iOS端播放mp4没有声音，Android端播放mp4正常的

### ISSUE THREAD

**Issue by 1284115201** [Tencent/vap#336]
iOS端播放mp4播放正常但是没有声音，Android端播放mp4正常是有声音的，我是用的flutter，两端用的同一个mp4文件

**Comment by jiarui236** [comment]
同问，iOS播放没有声音

**Comment by 1284115201** [comment]
> 同问，iOS播放没有声音

我这边刚确认了原生的iOS是播放有声音的，Flutter版本写的有问题

**Comment by 1284115201** [comment]
> 同问，iOS播放没有声音

确定了Flutter版本也没问题，是自己设置的问题

**Comment by 1284115201** [comment]
自己设置的问题

**Comment by 1284115201** [comment]
> 同问，iOS播放没有声音

路径不要有中文，要不然会出现安卓正常播放，苹果会播放不了声音问题
