### ISSUE TITLE
win10素材创建失败

### ISSUE THREAD

**Issue by Abao999** [Tencent/vap#337]
[ToolUI]:VAP tool 2.0.6
[ToolUI]:CommonArg{ffmpegCmd='win/ffmpeg', mp4editCmd='win/mp4edit', enableH265=false, fps=30, enableCrf=false, bitrate=2000, crf=29, scale=0.5, inputPath='F:\素材呗\视频\视频座驾', needAudio=false', audioPath='null'}
[AnimTool]:start create
[CommonArgTool]:Windows 10
[AnimTool]:createAllFrameImage
[AnimTool]:{"info":{"v":2,"f":308,"w":750,"h":1334,"fps":30,"videoW":1136,"videoH":1344,"aFrame":[754,0,375,667],"rgbFrame":[0,0,750,1334],"isVapx":0,"orien":0}}
[AnimTool]:run createMp4
[AnimTool]:createMp4 result=success
[Mp4BoxTool]:success
[AnimTool]:run mergeBin2Mp4
[ERROR]:
[AnimTool]:mergeBin2Mp4 result=fail
[AnimTool]:mergeBin2Mp4 fail
[AnimTool]:Finish cost=13812

**Comment by hexleo** [comment]
检查下mp4edit 工具是否能正常运行，可以参考wiki
https://github.com/Tencent/vap/wiki

**Comment by Abao999** [comment]
问题已解决，缺少系统文件140_1.dll
