### ISSUE TITLE
你好, 希望vap能够支持下渲染的 contentMode 

### ISSUE THREAD

**Issue by lixiaonan** [Tencent/vap#42]
很喜欢和支持vap这个框架, 目前也在使用vap. 但是由于一些业务场景的问题, 全屏显示的礼物动效, 在不同设备上会展示拉伸问题.
希望能支持下contentMode. 谢谢. vap框架很好, 赞一个

**Comment by hexleo** [comment]
在播放动画前，都会有一个准备开始的回调，这个回调里会告诉你VAP视频的宽高信息，这时候你可以手动调整view的大小，来进行适配。

**Comment by lixiaonan** [comment]
@hexleo 感谢你的回复.

**Comment by lixiaonan** [comment]
@hexleo 感谢您的回复. 目前我这边尝试下这样解决.  基于框架的易用性, 希望您未来方便考虑下我的这个建议

**Comment by hexleo** [comment]
以后可以优化

**Comment by hexleo** [comment]
Android 增加了设置ScaleType的接口，也支持自定义的ScaleType，应该可以满足你的要求

**Comment by githublsy** [comment]
> Android 增加了设置ScaleType的接口(2.0.13版本)，也支持自定义的ScaleType，应该可以满足你的要求

iOS呢

**Comment by hexleo** [comment]
iOS要晚点

**Comment by lixiaonan** [comment]
感谢作者更新!!

**Comment by lixiaonan** [comment]
> iOS要晚点

你好, 现在iOS支持了吗

**Comment by hexleo** [comment]
最新的ios版本已经支持

**Comment by lixiaonan** [comment]
> 最新的ios版本已经支持 1.0.6

您辛苦了, 多谢!

**Comment by lixiaonan** [comment]
> 最新的ios版本已经支持 1.0.6

你好, 我这边设置了contentMode = UIViewContentModeScaleAspectFill.

**Comment by lixiaonan** [comment]
> 最新的ios版本已经支持 1.0.6

你好, 我这边设置了contentMode = UIViewContentModeScaleAspectFill. 为啥还是会被压缩呢,

**Comment by 405092901** [comment]
> 最新的ios版本已经支持 1.0.6

iOS的设置全屏，ScaleType属性怎么没找到呢？
