### ISSUE TITLE
Android RecyclerView中应用VAP，特别卡。有没有好的解决方案

### ISSUE THREAD

**Issue by zhangzd1992** [Tencent/vap#45]
我在RecyclerView 中使用vap,当列表数据很多的时候，特别卡，卡到无法操作。VAP是不适合用在列表中展示么，还是在列表中应用需要有特别的设置

**Comment by hexleo** [comment]
TextureView不建议在列表中使用，因为RecyclerView（或ViewPager等）会自动回收重用。但卡不是很了解具体是怎么样的卡，你可以贴出一个测试demo代码，我看看
