### ISSUE TITLE
QGVAPConfigModel

### ISSUE THREAD

**Issue by NullWorld** [Tencent/vap#46]
#import <Foundation/Foundation.h>
#import <UIKit/UIkit.h>
#import <Metal/Metal.h>

引入的#import <UIKit/UIkit.h> 报错，大小写错误。。。

**Comment by hexleo** [comment]
可以提个pr修改

**Comment by casscqt** [comment]
> #import <Foundation/Foundation.h>
> #import <UIKit/UIkit.h>
> #import <Metal/Metal.h>
> 
> 引入的#import <UIKit/UIkit.h> 报错，大小写错误。。。

已修改，感谢反馈
