### ISSUE TITLE
某些mp4解码失败：  onFailed errorType=10002, errorMsg=0x2 MediaCodec exception e=java.lang.IllegalStateException

### ISSUE THREAD

**Issue by JerryIreya** [Tencent/vap#48]
https://qiniustatic.wodidashi.com/h5/front-backstage/maodian_1611720341327.mp4
上边这个视频解码失败，帮看下什么问题。

**Comment by hexleo** [comment]
现在发现我们导出的带锚点的视频在demo中播不了，报如下错：
E/AnimPlayer.Decoder: onFailed errorType=10002, errorMsg=0x2 MediaCodec exception e=java.lang.IllegalStateException
I/AnimPlayer.HardDecoder: release
E/AnimPlayer.HardDecoder: release e=java.lang.IllegalStateException

**Comment by hexleo** [comment]
我这用小米mix3，能正常播放，估计是兼容问题。你的视频分辨率太高了，已经快到4k，低端机很可能就无法播放了，建议你降低分辨率。而且分辨率太高，码率不变的情况下，你的视频质量也降低了。
![image](https://user-images.githubusercontent.com/3285051/106078489-7b5d7d80-614e-11eb-8676-f61726cd1a1d.png)
