### ISSUE TITLE
window版无法导出MP4

### ISSUE THREAD

**Issue by poonyy** [Tencent/vap#56]
[ToolUI]:CommonArg{ffmpegCmd='win/ffmpeg', mp4editCmd='win/mp4edit', enableH265=false, fps=24, bitrate=2000, scale=0.5, inputPath='C:\Users\Administrator\Desktop\vapx_demo\png', needAudio=false', audioPath='null'}
[AnimTool]:start create
[CommonArgTool]:Windows 10
[AnimTool]:createAllFrameImage
[AnimTool]:{"info":{"v":2,"f":120,"w":752,"h":752,"fps":24,"videoW":1136,"videoH":752,"aFrame":[756,0,376,376],"rgbFrame":[0,0,752,752],"isVapx":0,"orien":0}}
[AnimTool]:run createMp4
[AnimTool]:createMp4 result=success
[Mp4BoxTool]:success
[AnimTool]:run mergeBin2Mp4
[ERROR]:
[AnimTool]:mergeBin2Mp4 result=fail
[AnimTool]:mergeBin2Mp4 fail
[AnimTool]:Finish cost=5318

**Comment by hexleo** [comment]
win/mp4edit 应该是这个命令执行失败了，你可以本地cmd运行下这个命令，看看是否能运行

**Comment by poonyy** [comment]
![image](https://user-images.githubusercontent.com/71955411/108677736-0f8bec00-7525-11eb-8838-8acdfc714e8a.png)

**Comment by hexleo** [comment]
缺失VCRUNTIME140_1.dll文件导致，可以在别人电脑上拷贝或上网下载，也可以网上搜索下这个问题，网上有解决方法

**Comment by poonyy** [comment]
666感谢组织

**Comment by Dinamohy** [comment]
i have the same issue from where i can download the VCRUNTIME140_1.dll file
