### ISSUE TITLE
循环播放

### ISSUE THREAD

**Issue by daixiansen** [Tencent/vap#58]
大佬，android端能支持循环播放吗？ 我看ios是支持的呢。

**Comment by hexleo** [comment]
有个setLoop的接口

**Comment by daixiansen** [comment]
> 有个setLoop的接口

setLoop接口是设置循环播放次数的呢

**Comment by hexleo** [comment]
你可以设置int的最大值就好

**Comment by daixiansen** [comment]
> 你可以设置int的最大值就好
现在就是这么做的呢
