### ISSUE TITLE
errorType = 1004

### ISSUE THREAD

**Issue by MyLullaby** [Tencent/vap#60]
errorMsg = 0x4 e=java.lang.RuntimeException: Error creating shader.
怎么回事呢，如何修复？

**Comment by hexleo** [comment]
已经qq联系，是业务方宽高设置错误，到宽度为0导致

**Comment by W-quan** [comment]
RecyclerView 刷新，等待onVideoComplete， 重新播放也遇到了

**Comment by hexleo** [comment]
> RecyclerView 刷新，等待onVideoComplete， 重新播放也遇到了。 但是宽高是正常的。 最新版本
> 
> ```
> E/AnimPlayer.EGLUtil: error:3000
> E/AnimPlayer.Decoder: onFailed errorType=10004, errorMsg=0x4 render create fail e=java.lang.RuntimeException: Error creating shader.
> ```

你可以提个新的issue跟进，复现路径描述，完整的log日志，版本信息等
