### ISSUE TITLE
融合动效为啥字这么大呢？

### ISSUE THREAD

**Issue by tomatoK** [Tencent/vap#68]
issue 模版
1 问题描述：融合动效为啥字这么大呢？怎么调整可以把字做小
2 运行环境：
   iOS
3 相关日志
4 播放错误的文件：
   链接:https://pan.baidu.com/s/11AF5QYfKt6KvR9cdQ8fBDQ  密码:w9zg

**Comment by hexleo** [comment]
![image](https://user-images.githubusercontent.com/3285051/112432833-62530080-8d7c-11eb-9eb3-01d887d22743.png)
你们的遮罩图片太模糊了吧，遮罩黑色部分应该是边缘明确的，因为整个遮罩不透明部分表示，该元素在最终渲染图像里的坐标位置，可以参考https://github.com/Tencent/vap/tree/master/tool/vapx_demo demo

**Comment by hexleo** [comment]
小建议，如果你们要显示富文本的文字，建议你们自己做文字的bitmap，当作图片使用
