### ISSUE TITLE
mp4动画播放完了, 为啥会有一张图片没用在view上面消失呢, 居然还保留了

### ISSUE THREAD

**Issue by lixiaonan** [Tencent/vap#69]
issue 模版
1 问题描述（重现路径）
播放mp4动画结束后, 居然还有一张图不会在view上消失
2 运行环境（手机型号，Android/iOS版本等）
iOS14.2
3 相关日志
4 播放错误的文件（可选）
https://img.whyd888.com/FtE3zdpMLW0HQ0axVGFnizLZHiXd?imageslim

**Comment by hexleo** [comment]
你的链接打不开，可以把问题描述前粗些，是Android还是iOS的问题？日志可以贴一下

**Comment by lixiaonan** [comment]
> 你的链接打不开，可以把问题描述前粗些，是Android还是iOS的问题？日志可以贴一下

不好意思, 我这边描述清楚下. 是iOS的问题.

**Comment by Styx-S** [comment]
目前iOS侧实现在播放完后不会自动清除显示的内容
推荐的使用方式是viewDidStopPlayMP4:view:的回调当中把这个view从视图层级中移除

**Comment by Tongziqi** [comment]
> 目前iOS侧实现在播放完后不会自动清除显示的内容
> 推荐的使用方式是viewDidStopPlayMP4:view:的回调当中把这个view从视图层级中移除

那，其实`- (void)playHWDMp4:(NSString *)filePath;`这个方法基本上就用不上了，因为播放后view不消失，会挡住所有的操作
