### ISSUE TITLE
请问 web端融合参数如何传递

### ISSUE THREAD

**Issue by 471417811** [Tencent/vap#71]
问题描述：
视频文件config.json是这一段（取自demo视频4），一个文字参数是 name
"src": [
        {
            "srcId": "1",
            "srcType": "txt",
            "loadType": "local",
            "srcTag": "[name]",
            "color": "#ffffff",
            "style": "b",
            "w": 187,
            "h": 40,
            "fitType": "fitXY"
        }
    ]
融合参数ext传值：ext:{name:"我是一个名字"}
但是此参数并未传入，效果还是没有显示名字，我看官方的demo也是没有把名字显示出来的，这是demo本身的问题还是视频的问题呢
官方demo地址：https://egame.qq.com/vap

**Comment by hujinliang** [comment]
参数直接传name: 'xxx'就可以了
