### ISSUE TITLE
某些机型出现播放大动画一直崩溃的情况

### ISSUE THREAD

**Issue by 19snow93** [Tencent/vap#74]
1 问题描述：播放大动画一直出现崩溃
2 运行环境：Android9 华为m20 
3 相关日志：0x4 render create fail e=java.lang.RuntimeException: Error creating shader.

**Comment by hexleo** [comment]
能给出当时播放的详细日志吗？单是一个错误，很难定位具体问题，顺便你发下具体素材，我看看能不能重现

**Comment by 19snow93** [comment]
没有，根本捕捉不了日志，很莫名的崩溃

**Comment by hexleo** [comment]
这个错误“0x4 render create fail e=java.lang.RuntimeException: Error creating shader.”表示创建渲染环境失败，失败的原因有很多，比如显存不足等，但并不会crash，现象只是无法播放。如果你们有crash上报的话，应该能拿到堆栈

**Comment by ChanChuan0317** [comment]
那怎么处理的呢？
