### ISSUE TITLE
web下如何让动画在微信中自动播放

### ISSUE THREAD

**Issue by evollhhan** [Tencent/vap#75]
issue 模版
1 问题描述（重现路径）
在项目中应用，前面是有用户手指交互的前置路径的，在一些手机浏览器或者app中切换到动画场景时都可以自动播放，但是在微信下好像不行，有什么解决办法吗？

2 运行环境（手机型号，Android/iOS版本等）
无

3 相关日志
无

4 播放错误的文件（可选）
无

**Comment by hexleo** [comment]
不建议在手机的WebView上播放VAP，这个问题可以找 @hujinliang 帮忙看看

**Comment by evollhhan** [comment]
为什么不建议呢？是因为视频原因（如不能自动播放，唤起系统播放器覆盖全屏），还是性能相关的问题。另外想了解下两个小问题：
1. 我想把多段动画合并成一个视频，是不是通过控制video标签播放的时间就可以控制进度？
2. 如果项目中同时使用Pixi或者Three绘制其他场景，不会相互有影响吧？

谢谢。

项目很赞，相比较复杂效果用序列帧，的确省了太多时间。想到如果真要用png序列帧，参考这种解决方式，使用mask-image可能也可以这么搞搞，哈哈。

**Comment by hujinliang** [comment]
可能是因为微信禁止了video的自动播放？你试试以同样的路径，动态创建一个video看看video能不能正常播放

**Comment by lizy0329** [comment]
> 为什么不建议呢？是因为视频原因（如不能自动播放，唤起系统播放器覆盖全屏），还是性能相关的问题。另外想了解下两个小问题：
> 
> 1. 我想把多段动画合并成一个视频，是不是通过控制video标签播放的时间就可以控制进度？
> 2. 如果项目中同时使用Pixi或者Three绘制其他场景，不会相互有影响吧？
> 
> 谢谢。
> 
> 项目很赞，相比较复杂效果用序列帧，的确省了太多时间。想到如果真要用png序列帧，参考这种解决方式，使用mask-image可能也可以这么搞搞，哈哈。

本质上就是个 video， 所以会被各种浏览器劫持
