### ISSUE TITLE
同一个视频文件，iOS播放正常，背景色是全透明的；Android播放不正常，背景色依旧存在

### ISSUE THREAD

**Issue by yufengzungzhe** [Tencent/vap#76]
[log.txt](https://github.com/Tencent/vap/files/6381544/log.txt)

**Comment by yufengzungzhe** [comment]
https://user-images.githubusercontent.com/13448506/116178324-eddafb00-a747-11eb-9aa6-c4c6ba611db3.mp4

**Comment by hexleo** [comment]
在没开启GL_BLEND模式下会出现此问题，应该是之前alpha通道处理有问题导致。给出两个解决办法：1） 使用我们提供的最新版本工具进行生成，你这个视频应该不是用我们工具生成的，因为左边部分应该透明的区域应该是黑色才对；2）我们会在新版本修复此问题，但这个修复方案会导致老版本无法兼容新版本素材，这个部分还需要考虑下。

**Comment by hexleo** [comment]
这里思考了下，建议你使用第一个解决办法。第二个解决方法暂时不能上线，因为改动后会导致老版本不兼容（老版本播放新版本素材出现异常）虽然alpha通道处理确实有些问题，但配合我们的生成工具是没有问题的，之后我们会想个方法尽量进行兼容。

猜测这个视频是你们自己制作的吧，因为rgb部分透明部分不是黑色，如果你要自己制作视频需要将透明部分也做成黑色。而且你这个动画效果很简单，分辨率没必要做这么大，960建议减少1/3 或 1/2 效果应该差不多

**Comment by hexleo** [comment]
if ( gl_FragColor.a < 0.01 ){ discard; }
