### ISSUE TITLE
web 使用 demo中的素材安卓微信内声音播放了，但没画面显示

### ISSUE THREAD

**Issue by WeiFree** [Tencent/vap#77]
在安卓浏览器以及ios上是正常的，但是在微信内就只有声音没有画面

**Comment by hujinliang** [comment]
直接运行demo可以正常播放吗，我这边安卓微信中是正常的，可能微信对video有些特殊的限制

**Comment by WeiFree** [comment]
> 直接运行demo可以正常播放吗，我这边安卓微信中是正常的，可能微信对video有些特殊的限制

运行demo也是同样只有声音，没有画面。可能是微信限制吧
