### ISSUE TITLE
请问iOS resumeHWDMP4 啥时候能解决

### ISSUE THREAD

**Issue by unknowntc** [Tencent/vap#83]

**Comment by Styx-S** [comment]
之前调用pause会走入stop逻辑
目前去除了这个限制（iOS1.0.8），可以更新试一下
但是pause后退后台仍然会stop

**Comment by unknowntc** [comment]
请问退后台能否不暂停或者进前台还能播放

**Comment by unknowntc** [comment]
> 之前调用pause会走入stop逻辑
> 目前去除了这个限制（iOS1.0.8），可以更新试一下
> 但是pause后退后台仍然会stop

请问退后台能否不暂停或者进前台还能播放

**Comment by Styx-S** [comment]
tag: iOS1.0.9
已支持iOS退后台了（退后台时会暂停，回前台时恢复播放），可以试试

**Comment by unknowntc** [comment]
> tag: iOS1.0.9
> 已支持iOS退后台了（退后台时会暂停，回前台时恢复播放），可以试试

测过了吗？我试了，直接花屏了啊

**Comment by Styx-S** [comment]
> > tag: iOS1.0.9
> > 已支持iOS退后台了（退后台时会暂停，回前台时恢复播放），可以试试
> 
> 测过了吗？我试了，直接花屏了啊

可以贴下你的素材看看

**Comment by unknowntc** [comment]
> > > tag: iOS1.0.9
> > > 已支持iOS退后台了（退后台时会暂停，回前台时恢复播放），可以试试
> > 
> > 
> > 测过了吗？我试了，直接花屏了啊
> 
> 可以贴下你的素材看看

https://game-play.oss-cn-hangzhou.aliyuncs.com/uploadfile/2021/05/12/728ba08dd4843d41c11d2fa7d9c11de5.mp4

**Comment by Styx-S** [comment]
感谢反馈，这个问题已修复了，看看iOS1.0.10？

**Comment by unknowntc** [comment]
> 感谢反馈，这个问题已修复了，看看iOS1.0.10？

能否 播放到2s了，后台停留3s，再进入前台从第5s开始播放

**Comment by Styx-S** [comment]
> 能否 播放到2s了，后台停留3s，再进入前台从第5s开始播放

这个需求不是很通用，应该不会支持，需要自己实现

**Comment by unknowntc** [comment]
> > 能否 播放到2s了，后台停留3s，再进入前台从第5s开始播放
> 
> 这个需求不是很通用，应该不会支持，需要自己实现

这个很常用啊，直播送礼物很及时性的，不可能送礼物，退后台，过半小时进去才显示动画
