### ISSUE TITLE
android端 IAnimListener 的 onComplete 回调问题

### ISSUE THREAD

**Issue by fdh19979** [Tencent/vap#89]
按照文档的介绍

onComplete的描述是，视频播放结束(失败也会回调onComplete)

经过检查，以下错误类型出错时只会调用onFailed，不会回调onComplete

Constant.REPORT_ERROR_TYPE_CREATE_THREAD 
Constant.REPORT_ERROR_TYPE_PARSE_CONFIG 
Constant.REPORT_ERROR_TYPE_CONFIG_PLUGIN_MIX 
Constant.REPORT_ERROR_TYPE_FILE_ERROR

目前是需要使用者在onFailed中判断一下，如果是以上code，手动调用一次onComplete

请问这个是需要修改的问题

**Comment by hexleo** [comment]
感谢反馈，已经在2.0.16版本修复此问题
