### ISSUE TITLE
H5播放 - 安卓6下报错

### ISSUE THREAD

**Issue by liumi98** [Tencent/vap#92]
# 具体信息

1. 使用Vap官方demo在安卓6下报错
2. 不限手机型号，低版本安卓即可复现（Android 6、Android 5）
3. 报错信息如图
![1DA848C57F059B260BFC6B8821269320](https://user-images.githubusercontent.com/30725896/119079310-72105d80-ba2a-11eb-87e3-6a9e7c81c459.jpg)
4. 播放错误的文件
mp4：https://user-images.githubusercontent.com/30725896/119079364-8eac9580-ba2a-11eb-97ea-3733b311ac98.mp4
json：https://github.com/Tencent/vap/blob/master/web/demo/src/components/demo.json
# 额外参考信息

1. 直接用H5 <video>标签在Android6可以正常播放
2. 用Vap在PC Chrome也能正常播放
3. 用Vap在Android6 报错

**Comment by hujinliang** [comment]
这个是视频播放失败的报错，尝试下直接用video去播放能不能播出视频
![image](https://user-images.githubusercontent.com/17648734/119119978-545ceb80-ba5e-11eb-9a11-3e2971bfe571.png)

**Comment by liumi98** [comment]
1.直接用H5 video标签可播放
2.用Vap在PC Chrome可播放
3.用Vap在Android6 报错

**Comment by hujinliang** [comment]
我这边试了下，用Android5.1下的Chrome(80.0)可以正常播放，系统自带的浏览器无法正常播放。看了下原因是：在一些低版本的浏览器下设置video的crossOrigin会导致视频播放失败，如果视频是同源的可以把这个设置去掉
![image](https://user-images.githubusercontent.com/17648734/119592305-cd679480-be0a-11eb-9ff3-003f22439b42.png)
不过我这边解决视频播放问题后依然无法播放，看了下是浏览器不支持这个项目所依赖的底层能力：视频纹理，这个看起来没法解决
![image](https://user-images.githubusercontent.com/17648734/119593708-04d74080-be0d-11eb-8bd1-23dc3ebf4750.png)
