### ISSUE TITLE
播放视频中图像变形，播放视频已提交

### ISSUE THREAD

**Issue by kyle0101** [Tencent/vap#94]
# issue 模版

1. 问题描述（重现路径）
2. 运行环境（手机型号，Android/iOS版本等）

https://user-images.githubusercontent.com/25294835/120278391-cc8da180-c2e7-11eb-927c-41e643c9feda.mp4

3. 相关日志
4. 播放错误的文件（可选）

# issue 

> 

- 

1. 

- [ ] template

1. Problem description 
2. Running environment (mobile phone model, Android/iOS version, etc.)
3. Logs
4. Error file (optional)

**Comment by hexleo** [comment]
能截图看看视频用VAP播放时是什么样的吗？看你贴的视频，应该是直接播放了原始的mp4视频

**Comment by kyle0101** [comment]
![Screenshot_20210602-150157](https://user-images.githubusercontent.com/25294835/120438406-eb596a00-c3b3-11eb-81bf-0673217c5135.jpg)
第一张图是设置FIT_CENTER的属性 ，有很宽的黑边
第二张播放是设置FIT_XY没黑边，但箭头标识处变形了
<img width="808" alt="WeChataa1c9cdf2cb4db4410a017d93d51cef9" src="https://user-images.githubusercontent.com/25294835/120438774-5c991d00-c3b4-11eb-86d0-66b203d107c8.png">

**Comment by hexleo** [comment]
你所指的是对齐模式（调用setScaleType接口进行设置）
FIT_CENTER 指的是按比例缩小到view能现实的区域（之所以左右有黑边，是因为缩小导致）
FIT_XY 指的是view的比例是多少，视频内容就是什么比例（view如果比视频宽，视频自然被拉伸）

这个属性可以参考ImageView的scaleType，概念是一样的

**Comment by hexleo** [comment]
你是不是设置了黑色背景？
