### ISSUE TITLE
vap 有服务端生成 sdk 吗

### ISSUE THREAD

**Issue by JeffreyBool** [Tencent/vap#95]
想要服务端动态生成图片，有这方面的 sdk 吗？ 或者对应的算法介绍

**Comment by lverniu777** [comment]
有动效生成工具：https://github.com/Tencent/vap/tree/master/tool，
需要前置安装FFmpeg：https://www.ffmpeg.org/
Mp4Edit:https://www.bento4.com/documentation/mp4edit/

大致原理是：用Java API将原素材的RGB和透明度分离，生成中间临时图片产物，然后使用FFmpeg将临时产物编码为视频，最后用mp4edit工具生成VAP mp4描述box，封装至mp4文件中
