### ISSUE TITLE
关于资源文件的加密

### ISSUE THREAD

**Issue by iostyle** [Tencent/vap#96]
对于资源文件的加密各位有什么方案吗，比如我不想自己应用内的资源被盗用，不是资源目录，下载后存储在存储卡内的

**Comment by iostyle** [comment]
Android

**Comment by hexleo** [comment]
加密属于业务测的事情了，你们可以按照自己的需求进行加解密。你可以实现此接口IFileContainer，来直接读取你的加密文件。

**Comment by iostyle** [comment]
> 加密属于业务测的事情了，你们可以按照自己的需求进行加解密。你可以实现此接口IFileContainer，来直接读取你的加密文件。

是的，只是向大家请教一下

**Comment by hexleo** [comment]
建议你在 Discussions 里新建一个讨论帖，可以试试Discussions的功能

**Comment by iostyle** [comment]
> 建议你在 Discussions 里新建一个讨论帖，可以试试Discussions的功能

👌
