### ISSUE TITLE
vap 有一个子线程更新 UI 的操作，会在 7.1 及以下系统 crash

### ISSUE THREAD

**Issue by zsyqdr** [Tencent/vap#98]
你们好，Android端有崩溃，7.1及以下版本，anim_decode_thread就是VAP里面的线程

# anim_decode_thread(37523)

android.view.ViewRootImpl$CalledFromWrongThreadException

Only the original thread that created a view hierarchy can touch its views.

解析原始
1
android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6877)
2
android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1030)
3
android.view.ViewGroup.invalidateChild(ViewGroup.java:5120)
4
android.view.View.invalidateInternal(View.java:12750)
5
android.view.View.invalidate(View.java:12714)
6
android.view.View.invalidateViewProperty(View.java:12834)

**Comment by hexleo** [comment]
你应该是在IAnimListener的监听里调用了view的invalidate，注意这里的回调都是在子线程，需要自己转到主线程去处理
![image](https://user-images.githubusercontent.com/3285051/121979943-abd04c00-cdbd-11eb-83be-d04b0dfccd26.png)
